### ISSUE TITLE
Pact server fails for requests that don't have Content-Type header

### ISSUE THREAD

**Issue by octavian-h** [DiUS/pact-jvm#1008]
I tried to update my current pact-jvm-server from 3.6.1 to 4.0.4, but for GET requests it fails with 500. Looking in the stacktrace I see there is a problem at au.com.dius.pact.server.Conversions.unfilteredRequestToPactRequest. This method reads Content-Type header for all types of requests. I think a better way is to check if this header exists and if it is missing use some default values like text/plain with charset UTF-8.

Below is the stacktrace from pact-jvm-server:4.0.4:
```
java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:40)
	at au.com.dius.pact.server.Conversions$.unfilteredRequestToPactRequest(Conversions.scala:53)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$.convertRequest(UnfilteredMockProvider.scala:27)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$$anonfun$intent$1.applyOrElse(UnfilteredMockProvider.scala:24)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$$anonfun$intent$1.applyOrElse(UnfilteredMockProvider.scala:23)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
	at unfiltered.response.Pass$PassingAttempt.attempt(pass.scala:65)
	at unfiltered.response.Pass$PassingAttempt.attempt$(pass.scala:65)
	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
	at unfiltered.response.Pass$.$anonfun$fold$1(pass.scala:48)
	at unfiltered.response.Pass$FunctionAttempt.apply(pass.scala:77)
	at unfiltered.netty.cycle.Plan.$anonfun$channelRead$3(plans.scala:68)
	at unfiltered.netty.cycle.Plan.catching(plans.scala:41)
	at unfiltered.netty.cycle.Plan.catching$(plans.scala:40)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$.catching(UnfilteredMockProvider.scala:19)
	at unfiltered.netty.cycle.Plan.$anonfun$channelRead$2(plans.scala:67)
	at unfiltered.netty.cycle.SynchronousExecution.executeIntent(deferrals.scala:23)
	at unfiltered.netty.cycle.SynchronousExecution.executeIntent$(deferrals.scala:23)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$.executeIntent(UnfilteredMockProvider.scala:19)
	at unfiltered.netty.cycle.Plan.$anonfun$channelRead$1(plans.scala:66)
	at unfiltered.netty.cycle.Plan.catching(plans.scala:41)
	at unfiltered.netty.cycle.Plan.catching$(plans.scala:40)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$.catching(UnfilteredMockProvider.scala:19)
	at unfiltered.netty.cycle.Plan.channelRead(plans.scala:65)
	at unfiltered.netty.cycle.Plan.channelRead$(plans.scala:61)
	at au.com.dius.pact.server.UnfilteredMockProvider$Routes$.channelRead(UnfilteredMockProvider.scala:19)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by uglyog** [comment]
How are you running the mock server? And what version of Java are you using?

**Comment by uglyog** [comment]
Actually, I see what you mean, don't worry about the previous comment.

**Comment by octavian-h** [comment]
Hi, thanks for fixing this issue. Can you look also on https://github.com/DiUS/pact-jvm/issues/956, the problem is related to this one and is in the same class au.com.dius.pact.server.Conversions. I send the input stream directly to unfilteredRequestToPactRequest without converting it to string and then back to a byte array. Below are my proposed changes:
```scala
def toBodyInputStream(request: HttpRequest[ReceivedMessage]) = {
    val gzip = request.headers(ContentEncoding.GZip.name)
    if (gzip.hasNext && gzip.next().contains("gzip")) {
      new GZIPInputStream(request.inputStream)
    } else {
      request.inputStream
    }
  }

  def unfilteredRequestToPactRequest(request: HttpRequest[ReceivedMessage]): Request = {
    val headers = toHeaders(request)
    val contentTypeHeader = request.headers("Content-Type")
    val contentType = if (contentTypeHeader.hasNext) new ContentType(contentTypeHeader.next())
      else ContentType.getTEXT_PLAIN
    val is = toBodyInputStream(request)
    val body = if(is == null) OptionalBody.empty()
      else OptionalBody.body(org.apache.commons.io.IOUtils.toByteArray(is), contentType)
    new Request(request.method, toPath(request.uri), toQuery(request), headers, body)
  }
```

**Comment by uglyog** [comment]
Done

**Comment by uglyog** [comment]
version 4.0.7 has been released
