### ISSUE TITLE
Requests do not match when adding a json body

### ISSUE THREAD

**Issue by beatrichartz** [DiUS/pact-jvm#1080]
When running a simple request against the mock server, it works when not expecting a body. It fails when I add a json body with an expected value.

I believe it mismatches on the content type header, though I'm not sure how:

```kotlin
@Rule @JvmField
val provider = PactProviderRule("api_provider", this)

@Pact(consumer="app")
fun pact(builder: PactDslWithProvider): RequestResponsePact {
    return builder
       // request
       .uponReceiving("a request")
       .path("/request")
       .method("POST")
       .body(PactDslJsonBody().stringValue("a", "b"))
        // response
        .willRespondWith()
        .status(HttpStatus.SC_NO_CONTENT)
        .toPact()
}

@Test
@PactVerification
fun `verifies pact`() = runBlockingTest {
     Api().request()
}
```

```
[main] DEBUG au.com.dius.pact.consumer.BaseJdkMockServer - Starting mock server
[main] DEBUG au.com.dius.pact.consumer.BaseJdkMockServer - Mock server started: /127.0.0.1:55524
[Thread-2] DEBUG au.com.dius.pact.consumer.BaseJdkMockServer - Received request: 	method: POST
	path: /request
	query: {}
	headers: {Accept=[application/json], Connection=[keep-alive], Host=[localhost:55524], Pragma=[no-cache], User-agent=[Java/1.8.0_212-release], Content-type=[application/json; charset=utf-8] Content-length=[29], Cache-control=[no-cache]}
	matchers: MatchingRules(rules={})
	generators: Generators(categories={})
	body: PRESENT({"a":"b"})
[Thread-2] DEBUG au.com.dius.pact.core.matchers.RequestMatching - comparing to expected request: 
	method: POST
	path: /request
	query: {}
	headers: {Content-Type=[application/json; charset=UTF-8]}
	matchers: MatchingRules(rules={body=Category(name=body, matchingRules={})})
	generators: Generators(categories={})
	body: PRESENT({"a":"b"})
[Thread-2] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'Content-Type': 'application/json; charset=utf-8' to 'application/json; charset=UTF-8'
[Thread-2] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing content type header: 'application/json; charset=utf-8' to 'application/json; charset=UTF-8'
[main] DEBUG au.com.dius.pact.consumer.BaseJdkMockServer - Mock server shutdown


au.com.dius.pact.consumer.PactMismatchesException: The following requests were not received:
	method: POST
	path: /request
	query: {}
	headers: {Content-Type=[application/json; charset=UTF-8]}
	matchers: MatchingRules(rules={body=Category(name=body, matchingRules={}), path=Category(name=path, matchingRules={}), header=Category(name=header, matchingRules={})})
	generators: Generators(categories={})
	body: PRESENT({"a":"b"})

	at au.com.dius.pact.consumer.junit.JUnitTestSupport.validateMockServerResult(JUnitTestSupport.kt:60)
	at au.com.dius.pact.consumer.junit.BaseProviderRule.validateResult(BaseProviderRule.java:177)
	at au.com.dius.pact.consumer.junit.BaseProviderRule$1.evaluate(BaseProviderRule.java:84)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by beatrichartz** [comment]
Correction, this also happens on adopt-openjdk-8u242-b08

**Comment by beatrichartz** [comment]
Was able to fix this, the issue was in another library. Closing this.
