### ISSUE TITLE
 java.lang.NoSuchMethodError: kotlin.io.ByteStreamsKt.readBytes

### ISSUE THREAD

**Issue by eustimenko** [DiUS/pact-jvm#1083]
Have an error after migrating junit4 pact consumer to junit5

```
Exception in thread "Thread-6" java.lang.NoSuchMethodError: kotlin.io.ByteStreamsKt.readBytes(Ljava/io/InputStream;)[B
	at au.com.dius.pact.consumer.BaseJdkMockServer.toPactRequest(MockHttpServer.kt:227)
	at au.com.dius.pact.consumer.BaseJdkMockServer.handle(MockHttpServer.kt:198)
```

Any ideas, what I should do?

**Comment by uglyog** [comment]
Can you confirm the version of Kotlin you have in your project? What build tool are you using?
