### ISSUE TITLE
JUnit: Multiple test cases in the same test suite produce: MergeConflict error

### ISSUE THREAD

**Issue by peterlitvak** [DiUS/pact-jvm#114]
Say there is a test suite with two test cases:
```
public class PactTest {

    @Test
    public void testResponseCodeOnlyPact() {

        PactFragment pactFragment = ConsumerPactBuilder.
                .consumer("consumer1")
                .hasPactWith("provider1")
                .uponReceiving("a request to say Hello")
                .path("/hello")
                .method("POST")
                .body("{}")
                .willRespondWith()
                .status(400)
                .toFragment();
         ...
        assertEquals(ConsumerPactTest.PACT_VERIFIED, result); 
    }

    @Test
    public void testResponseWithBodyPact() {

        PactFragment pactFragment = ConsumerPactBuilder.
                .consumer("consumer1")
                .hasPactWith("provider1")
                .uponReceiving("a request to say Hello")
                .path("/hello")
                .method("POST")
                .body("{\"name\": \"harry\"}")
                .willRespondWith()
                .status(200)
                .body("{\"hello\": \"harry\"}", "application/json")
                .toFragment();

        ...
        assertEquals(ConsumerPactTest.PACT_VERIFIED, result); 
    }
```
And this produces the following exception:
```
java.lang.IllegalArgumentException: requirement failed: The following merge conflicts occurred: 
MergeConflict(ArrayBuffer((Interaction: a request to say Hello...
...
at scala.Predef$.require(Predef.scala:219)
	at au.com.dius.pact.consumer.PactGenerator.writeAllToFile(PactGenerator.scala:73)
	at au.com.dius.pact.consumer.ConsumerPactRunner$$anonfun$writeIfMatching$2.apply(ConsumerPactRunner.scala:13)
	at au.com.dius.pact.consumer.ConsumerPactRunner$$anonfun$writeIfMatching$2.apply(ConsumerPactRunner.scala:12)
	at scala.util.Success.foreach(Try.scala:235)
	at scala.util.Try$WithFilter.foreach(Try.scala:139)
	at au.com.dius.pact.consumer.ConsumerPactRunner$.writeIfMatching(ConsumerPactRunner.scala:12)
	at au.com.dius.pact.consumer.ConsumerPactRunner$.writeIfMatching(ConsumerPactRunner.scala:9)
	at au.com.dius.pact.consumer.ConsumerPactRunner$$anonfun$runAndWritePact$2.apply(ConsumerPactRunner.scala:32)
	at au.com.dius.pact.consumer.ConsumerPactRunner$$anonfun$runAndWritePact$2.apply(ConsumerPactRunner.scala:32)
	at scala.Option.fold(Option.scala:157)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:32)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at com.copyright.pact.PactTest.testPact(PactTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by peterlitvak** [comment]
Clarification: If you add a provider state via given() directive then everything is written to the interaction file without any errors. So effectively this forces to have provider states specified for each test case which is not ideal.

**Comment by uglyog** [comment]
This is an issue with the way the PactSession works. I've come across it quite a few times. The main problem is it uses description and provider state as a key, and if it gets an interaction with the same key but different values, it raises this error.

It treats the key as a unique ID so it can replace the interaction in the pact file instead of creating duplicates. One work around is to have each test have a unique description. For example:

```java
public class PactTest {

    @Test
    public void testResponseCodeOnlyPact() {

        PactFragment pactFragment = ConsumerPactBuilder.
                .consumer("consumer1")
                .hasPactWith("provider1")
                .uponReceiving("a request to say Hello with a response code only")
                .path("/hello")
                .method("POST")
                .body("{}")
                .willRespondWith()
                .status(400)
                .toFragment();
         ...
        assertEquals(ConsumerPactTest.PACT_VERIFIED, result); 
    }

    @Test
    public void testResponseWithBodyPact() {

        PactFragment pactFragment = ConsumerPactBuilder.
                .consumer("consumer1")
                .hasPactWith("provider1")
                .uponReceiving("a request to say Hello with a body")
                .path("/hello")
                .method("POST")
                .body("{\"name\": \"harry\"}")
                .willRespondWith()
                .status(200)
                .body("{\"hello\": \"harry\"}", "application/json")
                .toFragment();

        ...
        assertEquals(ConsumerPactTest.PACT_VERIFIED, result); 
    }
```

**Comment by peterlitvak** [comment]
Yep, that works. Thank you!
