### ISSUE TITLE
Gson java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by wayofthepie** [DiUS/pact-jvm#1180]
It seems #1077 is still an issue. I'm using the latest versions which are mentioned in that issue, at least I think I am, there are a lot of different versions now so it's not currently clear:
```
    testImplementation('au.com.dius.pact:provider:4.1.6')
    testImplementation('au.com.dius.pact.provider:junit5:4.1.6')
    testImplementation('au.com.dius.pact.provider:junit5spring:4.1.6')
```
And I'm still seeing the below:
```   
 java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'
        at au.com.dius.pact.provider.ResponseComparison$Companion.generateFullDiff(ResponseComparison.kt:89)
        at au.com.dius.pact.provider.ResponseComparison$Companion.access$generateFullDiff(ResponseComparison.kt:83)
        at au.com.dius.pact.provider.ResponseComparison.bodyResult(ResponseComparison.kt:78)
        at au.com.dius.pact.provider.ResponseComparison$Companion.compareResponse(ResponseComparison.kt:122)
        at au.com.dius.pact.provider.ProviderVerifier.verifyRequestResponsePact(ProviderVerifier.kt:521)
        at au.com.dius.pact.provider.junit5.PactVerificationContext.validateTestExecution(PactJUnit5VerificationProvider.kt:117)
        at au.com.dius.pact.provider.junit5.PactVerificationContext.verifyInteraction(PactJUnit5VerificationProvider.kt:90)
```
I guess, are the versions correct? Or is this an issue in the latest also? Thanks!

**Comment by uglyog** [comment]
4.1.7 has been released with Gson totally removed

**Comment by wayofthepie** [comment]
Looks good now thanks! Will close this issue.
