### ISSUE TITLE
Question: Verify the http status code 400 failed

### ISSUE THREAD

**Issue by stephenwang1011** [DiUS/pact-jvm#1192]
Dear Author,
   I'm trying to verify the PACT with status code 400 but I'm unable to generate a PACT because of its failing due to mocked server.
  I also refer to this article:[https://github.com/DiUS/pact-jvm/issues/589](https://github.com/DiUS/pact-jvm/issues/589). But it didn't help me.
Here is my code, pls help me. I will be very appreciative!

```
@RunWith(SpringRunner.class)
@SpringBootTest
public class LoginTest {
```
    @Autowired
    NeuronPublicService neuronPublicService;

    private void checkResult(PactVerificationResult result) {
        if (result instanceof PactVerificationResult.Error) {
            throw new RuntimeException(((PactVerificationResult.Error) result).getError());
        }
      assertThat(result,is(instanceOf(PactVerificationResult.Ok.class)));
    }

    @Test(expected = HttpResponseException.class)
    public void testLoginFail() throws Exception {
        Map<String, String> responseHeaders = new HashMap<String, String>();
        responseHeaders.put("Content-Type", "application/json;charset=UTF-8");

        DslPart responseBody = new PactDslJsonBody()
            .stringValue("message","Something went wrong. Please try again later")
            .stringValue("detailed","We are experiencing some technical difficulties. Please try again later.Bad credential.")
            .stringValue("errorCode","INVALID_REQUEST")
            .timestamp("timestamp")
            .object("data");

        DslPart requestBody = new PactDslJsonBody()
            .stringValue("username","18672701969")
            .stringValue("password","0000");

        RequestResponsePact pact = ConsumerPactBuilder
            .consumer("LoginError")
            .hasPactWith("NeuronPublic")
            .given("")
            .uponReceiving("Bad credential.")
            .path("/api/auth/login")
            .headers("Content-Type","application/json")
            .method("POST")
            .body(requestBody)
            .willRespondWith()
            .headers(responseHeaders)
            .status(400)
            .body(responseBody)
            .toPact();

        MockProviderConfig config = MockProviderConfig.createDefault(PactSpecVersion.V3);

        PactVerificationResult result = runConsumerTest(pact, config, (mockServer,context) -> {
            neuronPublicService.setBackendURL(mockServer.getUrl());
            LoginErrorResponse loginErrorResponse = neuronPublicService.getLoginErrorResponseInfo();
            assertEquals("We are experiencing some technical difficulties. Please try again later.Bad credential.", loginErrorResponse.getDetailed());
            return null;
        });

        checkResult(result);
    }`

When I run the command:
`./gradlew clean test`

I will get the below error:
`java.lang.Exception: Unexpected exception, expected<org.apache.http.client.HttpResponseException> but was<java.lang.RuntimeException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"data":{},"detailed":"We are experiencing some technical difficulties. Please try again later.Bad credential.","errorCode":"INVALID_REQUEST","message":"Something went wrong. Please try again later","timestamp":"2020-08-22T20:20:18"}]
	at com.rideneuron.userapppact.LoginTest.checkResult(LoginTest.java:41)
	at com.rideneuron.userapppact.LoginTest.testLoginFail(LoginTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 45 more
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"data":{},"detailed":"We are experiencing some technical difficulties. Please try again later.Bad credential.","errorCode":"INVALID_REQUEST","message":"Something went wrong. Please try again later","timestamp":"2020-08-22T20:20:18"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:418)
	at com.rideneuron.userapppact.service.NeuronPublicService.getLoginErrorResponseInfo(NeuronPublicService.java:33)
	at com.rideneuron.userapppact.LoginTest.lambda$testLoginFail$1(LoginTest.java:130)
	at au.com.dius.pact.consumer.BaseMockServer.runAndWritePact(MockHttpServer.kt:110)
	at au.com.dius.pact.consumer.ConsumerPactRunnerKt.runConsumerTest(ConsumerPactRunner.kt:13)
	at com.rideneuron.userapppact.LoginTest.testLoginFail(LoginTest.java:128)
	... 56 more`

What am I wrong?
Hi @uglyog, hope you can reply and help me. Thank you!

**Comment by stephenwang1011** [comment]
@uglyog  hi Could you please help to have a look? Thanks so much!

**Comment by stephenwang1011** [comment]
I try... catch the below code, it works. Now  I  can generate the pact file where the HTTP status is 400
![image](https://user-images.githubusercontent.com/3350356/91017383-c06e0880-e620-11ea-830b-75e956b758cc.png)

**Comment by uglyog** [comment]
It was not failing due to mocked server. The mock server has behaving correctly. Your HTTP client library was throwing the exception because it got a non-20x response. Handling the exception in the test is the correct way to deal with it.
