### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sydseter** [DiUS/pact-jvm#1230]
I am seeing:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuffer.append(StringBuffer.java:381)
	at java.io.StringWriter.write(StringWriter.java:77)
	at org.json.JSONArray.write(JSONArray.java:1112)
	at org.json.JSONObject.writeValue(JSONObject.java:1747)
	at org.json.JSONObject.write(JSONObject.java:1827)
	at org.json.JSONObject.writeValue(JSONObject.java:1745)
	at org.json.JSONArray.write(JSONArray.java:1105)
	at org.json.JSONObject.writeValue(JSONObject.java:1747)
	at org.json.JSONObject.write(JSONObject.java:1810)
	at org.json.JSONObject.toString(JSONObject.java:1609)
	at org.json.JSONObject.toString(JSONObject.java:1586)
	at au.com.dius.pact.consumer.dsl.PactDslResponse.body(PactDslResponse.java:250)
	at com.example.IntegrationPact.pactRequestToSearchUserOK(IntegrationPact.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:198)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.lookupPact(PactConsumerTestExt.kt:339)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.setupMockServer(PactConsumerTestExt.kt:242)
	at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.resolveParameter(PactConsumerTestExt.kt:211)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:216)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:144)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:96)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:481)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$18(ClassBasedTestDescriptor.java:466)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda$230/1301352406.invokeBeforeEachMethod(Unknown Source)

This happens when I add the following pact:

    @Pact(consumer = "user", provider = "provider")
    public RequestResponsePact pactRequestToSearchUserOK(PactDslWithProvider builder) {
      //....
      .eachLike("topAccountList", 4356843)
      .closeArray()
     //....
    }

The issue goes away if I remove the two lines in the method above.

I am attaching system info, logs and one example class that work and the other with exception.
I am using the following dependencies:

        <dependency>
            <groupId>au.com.dius.pact.consumer</groupId>
            <artifactId>junit5</artifactId>
            <version>4.1.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>5.2.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test-autoconfigure</artifactId>
            <version>5.2.7.RELEASE</version>
            <scope>test</scope>
        </dependency>

[outofmemoryerror.zip](https://github.com/DiUS/pact-jvm/files/5391519/outofmemoryerror.zip)

**Comment by sydseter** [comment]
I see that I should use:

    .array("topAccountList").integerType(4356843L).closeArray()

instead.

**Comment by sydseter** [comment]
Still, you shou

**Comment by sydseter** [comment]
Still, you should look into avoiding the function running until the environment reach out-of-memory error.

**Comment by uglyog** [comment]
The second parameter to `eachLike` is the number of example values that should be populated in the list. So `.eachLike("topAccountList", 4356843)` will try create a list with over four million items in it. It's not surprising that results in an OutOfMemoryError.
