### ISSUE TITLE
pact-jvm-server throws ChannelPipelineException on subsequent /create request

### ISSUE THREAD

**Issue by timoreimann** [DiUS/pact-jvm#129]
Firing the `/create` request I mentioned in #128 twice against pact-jvm-server causes the server to crash with a `ChannelPipelineException` on the second attempt.

Here's the result of the first request

```
$ curl http://localhost:29999/create?state=none -X POST -d '{ "provider": { "name": "Provider" }, "consumer": { "name": "Consumer" }, "interactions": [ { "description": "A GET request against the producer", "request": { "method": "get", "path": "/producer", "headers": { "Content-Type": "application/json" } }, "response": { "status": 200, "headers": { "Content-Type": "application/json" } } } ], "metadata": { "pactSpecificationVersion": "1.0.0" } }'
{
  "error" : "please provide state param and pact body"
}
```

and here's the second one:

```
$ curl http://localhost:29999/create?state=none -X POST -d '{ "provider": { "name": "Provider" }, "consumer": { "name": "Consumer" }, "interactions": [ { "description": "A GET request against the producer", "request": { "method": "get", "path": "/producer", "headers": { "Content-Type": "application/json" } }, "response": { "status": 200, "headers": { "Content-Type": "application/json" } } } ], "metadata": { "pactSpecificationVersion": "1.0.0" } }'
curl: (52) Empty reply from server
```

And here's the log output of the server:

```
Jun 18, 2015 9:51:27 PM io.netty.channel.ChannelInitializer channelRegistered
WARNING: Failed to initialize a channel. Closing: [id: 0x93cd919f, /127.0.0.1:58095 => /127.0.0.1:29999]
io.netty.channel.ChannelPipelineException: au.com.dius.pact.server.RequestHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:463)
	at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:135)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:128)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
	at unfiltered.netty.Server$$anon$1$$anonfun$initChannel$1.apply(Server.scala:132)
	at unfiltered.netty.Server$$anon$1$$anonfun$initChannel$1.apply(Server.scala:130)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:136)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
	at unfiltered.netty.Server$$anon$1.initChannel(Server.scala:130)
	at unfiltered.netty.Server$$anon$1.initChannel(Server.scala:123)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by uglyog** [comment]
RequestHandler now has a @Sharable annotationm which fixes this issue

**Comment by timoreimann** [comment]
Working perfectly for me now. Thanks!
