### ISSUE TITLE
default to parsing producer response with UTF-8 encoding

### ISSUE THREAD

**Issue by timoreimann** [DiUS/pact-jvm#132]
Response content seems to be matched in ASCII encoding, or at least something which is not UTF-8. I needed to append a `charset=utf-8` field to the `Content-Type` header of the response in order to enforce UTF-8-based matching.

I'd argue that it's reasonable to use UTF-8 for matching purposes by default so that providers are not required to specify the charset explicitly.

I verified the behavior using pact-jvm-provider-sbt.

**Comment by uglyog** [comment]
That is surprising, I would have expected UTF-8 to be the default

**Comment by uglyog** [comment]
I'm unable to reproduce this. Could you describe the symptoms you are seeing, i.e., is it a particular type of matching like regex? Or could you post the debug logs of the failed test?

**Comment by uglyog** [comment]
Also, what type of bodies are you using pact with? I've assumed JSON.

**Comment by timoreimann** [comment]
Interestingly, it's not failing for me when I do regex or type based matching. However, literal string matching using the string "äöü" causes the issue to arise for me.

Yes, it's all JSON in the body.

Let me put together a reproducible example for you once I am in the office.

How do I have enable debug logging?

**Comment by uglyog** [comment]
debug logging is enabled through SLF4J. I'm not sure how to enable that in SBT, but a quick search on google indicates that it is quite easy.

**Comment by timoreimann** [comment]
I created a reproducible case using the [Finatra hello world example application](https://github.com/twitter/finatra/tree/master/examples/finatra-hello-world). I extended the example by adding a `/utf8` route returning `{ "result": "äöü" }`, updating Finatra to not add a charset header field (which it didn't do until Finatra 2), and creating Pact configuration and specification files.

Please try the following to reproduce the issue:

1. Check out my branch: `git clone --branch pact-jvm-utf-8-bug-issue-132 --single-branch https://github.com/timoreimann/finatra.git && cd finatra`
1. Start the hello world example: `sbt helloWorld/run`
1. Run the verification in a separate shell: `sbt verifyPacts`

This leads to the following verification error for me:

```
$ sbt verifyPacts
[info] Loading global plugins from /Users/treimann/.sbt/0.13/plugins
[info] Loading project definition from /Users/treimann/Development/repos/private/finatra/project
[info] Set current project to root (in build file:/Users/treimann/Development/repos/private/finatra/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Run starting. Expected test count is: 1
PactSpec:
- pact for consumer Consumer 
provider Producer 
interaction "a request"
in state: ""  *** FAILED ***
  There were response mismatches: 
  BodyMismatch(äöü,Ã¤Ã¶Ã¼,Some(Expected 'äöü' but received 'Ã¤Ã¶Ã¼'),$.body.result) (FreeSpec.scala:1740)
  org.scalatest.exceptions.TestFailedException:
  at au.com.dius.pact.provider.PactSpec$$anonfun$2$$anonfun$apply$1.apply$mcV$sp(PactSpec.scala:34)
  at au.com.dius.pact.provider.PactSpec$$anonfun$2$$anonfun$apply$1.apply(PactSpec.scala:18)
  at au.com.dius.pact.provider.PactSpec$$anonfun$2$$anonfun$apply$1.apply(PactSpec.scala:18)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:373)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
  at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1740)
  at org.scalatest.FreeSpecLike$class.invokeWithFixture$1(FreeSpecLike.scala:370)
  at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
  at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:382)
  at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1740)
  at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
  at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:318)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FreeSpecLike$class.runTests(FreeSpecLike.scala:441)
  at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1740)
  at org.scalatest.Suite$class.run(Suite.scala:1424)
  at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1740)
  at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:486)
  at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:486)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FreeSpecLike$class.run(FreeSpecLike.scala:486)
  at org.scalatest.FreeSpec.run(FreeSpec.scala:1740)
  at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1492)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1528)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1526)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
  at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1526)
  at org.scalatest.Sequential.org$scalatest$SequentialNestedSuiteExecution$$super$runNestedSuites(Sequential.scala:63)
  at org.scalatest.SequentialNestedSuiteExecution$class.runNestedSuites(SequentialNestedSuiteExecution.scala:41)
  at org.scalatest.Sequential.runNestedSuites(Sequential.scala:63)
  at org.scalatest.Suite$class.run(Suite.scala:1421)
  at org.scalatest.Sequential.run(Sequential.scala:63)
  at org.scalatest.Suite$class.execute(Suite.scala:843)
  at org.scalatest.Sequential.execute(Sequential.scala:63)
  at org.scalatest.ShellImpl.run(Shell.scala:405)
  at au.com.dius.pact.provider.Main$.runPacts(Main.scala:20)
  at PactJvmPlugin$$anonfun$3.apply(PactJvmPlugin.scala:16)
  at PactJvmPlugin$$anonfun$3.apply(PactJvmPlugin.scala:13)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
  at sbt.std.Transform$$anon$4.work(System.scala:63)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
  at sbt.Execute.work(Execute.scala:235)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Run completed in 674 milliseconds.
Total number of tests run: 1
Suites: completed 2, aborted 0
Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
[success] Total time: 1 s, completed 01.07.2015 12:57:18
```

Now, if you move my branch to `HEAD^` and try again, you should see the verification succeeding. At that commit, the charset header field _is_ appended and the Pact expectation updated accordingly. Verification run output:

```
$ sbt verifyPacts
[info] Loading global plugins from /Users/treimann/.sbt/0.13/plugins
[info] Loading project definition from /Users/treimann/Development/repos/private/finatra/project
[info] Set current project to root (in build file:/Users/treimann/Development/repos/private/finatra/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Run starting. Expected test count is: 1
PactSpec:
- pact for consumer Consumer 
provider Producer 
interaction "a request"
in state: "" 
Run completed in 577 milliseconds.
Total number of tests run: 1
Suites: completed 2, aborted 0
Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
[success] Total time: 1 s, completed 01.07.2015 12:55:15
```

Please let me know if this helps you identify the root cause, or whether you need additional information from me. I'll try to enable debug logging later and amend the ticket accordingly.

Thanks again!

**Comment by uglyog** [comment]
I got your test app to pass. It was an issue in both the SBT provider and the Gradle one, which use different HTTP Clients. So it might be the default behaviour defined by HTTP spec to use a ASCII charset if one is not defined.

**Comment by timoreimann** [comment]
You seem to be right: According to [this SO thread](http://stackoverflow.com/questions/2325571/for-http-responses-with-content-types-suggesting-character-data-which-charset-s), the default charset is ISO-8859-1 unless overridden. However, most browsers seem to ignore this and apply some means of auto-detection.

I'm not completely clear on how to move forward from here. I see multiple possible paths:

1. Respect the standard and rely on producers to set the proper charset. The drawback here is that other Pact users will likely run into the problem as well and need to deal with it. We'd probably have to document the case somewhere, such as in the FAQ. Additionally, users may not be able to modify the producer to include the proper charset.
1. Try to auto-detect the format. Not sure how easy or hard this is; I can imagine that it may come with a certain level of fuzziness.
1. Use UTF-8 unconditionally. I personally wouldn't build an API that uses any encoding other than UTF-8, but other people's mileages may vary.
1. Add a configuration parameter to the Pact specification by which the user can specify the encoding explicitly. One would need to come up with a idea on how to deal with the situation where both the encoding is specified in the specification and the response contains a charset. Apart from that, the approach would enable proper charset handling externally (i.e., without having to change the producer).

@uglyog, thoughts on any of these or other approaches?

**Comment by uglyog** [comment]
I'm happy with defaulting to UTF-8, as it is a super set of ASCII and ISO-8859-1, so any ISO-8859-1 encoded response can be safely parsed as UTF-8.

**Comment by uglyog** [comment]
Pushed version 2.2.6 with this fix

**Comment by timoreimann** [comment]
Sounds good. Thanks!
