### ISSUE TITLE
PactRule hides stack traces

### ISSUE THREAD

**Issue by cer** [DiUS/pact-jvm#140]
The code below catches exceptions and then calls fail(). This hides the stacktrace, which obscures where the test is failing. 
It would be better to not catch (some) exceptions and/or wrap and rethrow.
Seems related to #40.

```
               VerificationResult result = fragment.runConsumer(config, new TestRun() {

                    @Override
                    public void run(MockProviderConfig config) {
                        try {
                            base.evaluate();
                        } catch (Throwable e) {
                            fail("error thrown: "+e);
                        }
                    }
                });
```

**Comment by uglyog** [comment]
Probably better to let all exceptions propagate. Catching them and then wrapping serves no purpose that I can see.

**Comment by cer** [comment]
Great that you fixed this. When is the next scheduled released?

**Comment by uglyog** [comment]
I'll try fix #40 this weekend and then push a release out.

**Comment by cer** [comment]
Excellent! Thanks.

**Comment by uglyog** [comment]
version 2.2.10 has been pushed to maven central

**Comment by C-Otto** [comment]
This is still an issue with version 2.2.10. When throwing an exception in my test method, I get:

```
    @Test
    @PactVerification("state")
    public void test() throws Exception {
        client.sendRequest();
        Exception nestedException = new Exception("this is relevant information");
        throw new Exception("irrelevant information", nestedException);
    }

scala.MatchError: an instance of class au.com.dius.pact.consumer.UserCodeFailed
	at au.com.dius.pact.consumer.VerificationResult$class.toString(VerificationResult.scala:17)
	at au.com.dius.pact.consumer.UserCodeFailed.toString(VerificationResult.scala:50)
	at java.lang.String.valueOf(String.java:2982)
	at org.junit.Assert.format(Assert.java:843)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at au.com.dius.pact.consumer.PactRule$1.evaluate(PactRule.java:82)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
```

With version 2.2.9 this case at least shows the outermost/parent exception:

```
java.lang.RuntimeException: java.lang.AssertionError: error thrown: java.lang.Exception: irrelevant information
	at au.com.dius.pact.consumer.PactRule$1.evaluate(PactRule.java:82)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.AssertionError: error thrown: java.lang.Exception: irrelevant information
	at org.junit.Assert.fail(Assert.java:88)
	at au.com.dius.pact.consumer.PactRule$1$1.run(PactRule.java:76)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply$mcV$sp(PactFragment.scala:21)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply(PactFragment.scala:21)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply(PactFragment.scala:21)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:45)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:43)
	at scala.util.Try$.apply(Try.scala:191)
	at au.com.dius.pact.consumer.StatefulMockProvider.runAndClose(MockProvider.scala:42)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:28)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at au.com.dius.pact.consumer.PactRule$1.evaluate(PactRule.java:69)
	... 19 more
```

When not sending the request, but still throwing the exception, with version 2.2.10 I get another error just informing me about the missing but expected request.

**Comment by uglyog** [comment]
I've updated the PactRule to show both the mismatch and the exception:

```
au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:
The following requests where not received:
Interaction: ConsumerPactWithThriftMimeTypeTest test interaction
	in state Some(test state)
request:
	method: GET
	path: /persons/429605785802342400
	query: None
	headers: Some(Map(Accept -> application/x-thrift+json))
	matchers: None
	body:
None

response:
	status: 200 
	headers: Some(Map(Content-Type -> application/x-thrift+json)) 
	matchers: None 
	body: 
Some({"1":{"str":"429605785802342400"},"2":{"str":"ggloin"},"3":{"str":"1859"},"4":{"rec":{"1":{"str":"Gloin"},"2":{"str":"Gimli"}}},"5":{"rec":{"1":{"str":"City"},"2":{"str":"United States"},"3":{"str":"UTC+02:00 Eastern Europe"}}},"6":{"str":"http://xxx.com/Users:ggloin:PortraitUrl?AWSAccessKeyId=aaaa&Expires=2147483647&Signature=aaaa4%2B4%3D"},"7":{"str":"2014-02-01T13:22:52.585Z"},"8":{"str":"1"}})
	at au.com.dius.pact.consumer.PactRule$1.evaluate(PactRule.java:86)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.Exception: irrelevant information
	at au.com.dius.pact.consumer.ConsumerPactWithThriftMimeTypeTest.test(ConsumerPactWithThriftMimeTypeTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at au.com.dius.pact.consumer.PactRule$1$1.run(PactRule.java:73)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply$mcV$sp(PactFragment.scala:21)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply(PactFragment.scala:21)
	at au.com.dius.pact.model.PactFragment$$anonfun$runConsumer$1.apply(PactFragment.scala:21)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:46)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:44)
	at scala.util.Try$.apply(Try.scala:191)
	at au.com.dius.pact.consumer.StatefulMockProvider.runAndClose(MockProvider.scala:43)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:28)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at au.com.dius.pact.consumer.PactRule$1.evaluate(PactRule.java:69)
	... 19 more
Caused by: java.lang.Exception: this is relevant information
	at au.com.dius.pact.consumer.ConsumerPactWithThriftMimeTypeTest.test(ConsumerPactWithThriftMimeTypeTest.java:54)
	... 39 more
```

**Comment by C-Otto** [comment]
I'd like to see another newline:

```
body:
NoneThe following requests where not received:
```
