### ISSUE TITLE
ProviderVerifier throws GroovyCastException when v3 pact is used

### ISSUE THREAD

**Issue by venksub** [DiUS/pact-jvm#160]
I am trying out the v3 messaging verification. The pact json is generated correctly by the consumer side. However, when I tried the pact verification against the provider, I am getting this error:

Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'au.com.dius.pact.model.v3.messaging.MessagePact([au.com.dius.pact.model.v3.messaging.Message(an order confirmation message, provider-state, eyJ0ZXN0IjoidGVzdFZhbHVlIn0=, [:], [:])], Consumer(consumer), Provider(provider), [pact-jvm:[version:3.0.3], pact-specification:[version:3.0.0]])' with class 'au.com.dius.pact.model.v3.messaging.MessagePact' to class 'au.com.dius.pact.model.Pact'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.loadPactFileForConsumer(ProviderVerifier.groovy:85)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.runVerificationForConsumer(ProviderVerifier.groovy:50)

It seems to be originating at au.com.dius.pact.provider.ProviderVerifier.loadPactFileForConsumer because this method returns a "Pact" but in v3 messaging, the method will actually return a V3Pact (which is not a subclass of "Pact").

**Comment by uglyog** [comment]
I've pushed a fix for this issue.

**Comment by uglyog** [comment]
Version 3.0.4 with this fix has been released
