### ISSUE TITLE
 Request Failed - head of empty list with version 3.0.4

### ISSUE THREAD

**Issue by ChuanChuanLaw** [DiUS/pact-jvm#166]
Hi,

After upgrading from pact-jvm-provider-gradle_2.11 3.01 to 3.04, running pactVerify gives the following error:

 Request Failed - head of empty list

In debug mode, it says:

14:11:16.891 [DEBUG] [au.com.dius.pact.matchers.MinimumMatcher$] comparing List(
) with minimum 1 at List($, body, Features, 0, SubFeatures)
14:11:16.911 [QUIET] [system.out]       Request Failed - head of empty list
14:11:16.924 [QUIET] [system.out]
Failures:

**Comment by uglyog** [comment]
Could you run `pactVerify` with `-Ppact.showStacktrace` and provide the generated stack trace?

**Comment by ChuanChuanLaw** [comment]
[Using file C:\api\TradeApiTests\target\pacts\Retail Site-Data Service.json]
  Given Scenario of Retail Site is retrieving data from Data Service
         WARNING: State Change ignored as there is no stateChange URL
  a retrieve a Data Service request
      Request Failed - head of empty list
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:420)
        at scala.collection.immutable.Nil$.head(List.scala:417)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compareLists(JsonBodyMatche
r.scala:80)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compare(JsonBodyMatcher.sca
la:47)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareMaps$1.appl
y(JsonBodyMatcher.scala:115)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareMaps$1.appl
y(JsonBodyMatcher.scala:113)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221
)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:
428)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compareMaps(JsonBodyMatcher
.scala:113)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compare(JsonBodyMatcher.sca
la:45)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareListContent
$2.apply(JsonBodyMatcher.scala:65)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareListContent
$2.apply(JsonBodyMatcher.scala:63)
        at scala.collection.TraversableViewLike$Filtered$$anonfun$foreach$4.appl
y(TraversableViewLike.scala:197)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableViewLike$Transformed$class.foreach(IterableV
iewLike.scala:44)
        at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.
scala:37)
        at scala.collection.TraversableViewLike$Filtered$class.foreach(Traversab
leViewLike.scala:196)
        at scala.collection.SeqViewLike$$anon$5.foreach(SeqViewLike.scala:199)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compareListContent(JsonBody
Matcher.scala:63)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compareLists(JsonBodyMatche
r.scala:80)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compare(JsonBodyMatcher.sca
la:47)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareMaps$1.appl
y(JsonBodyMatcher.scala:115)
        at au.com.dius.pact.matchers.JsonBodyMatcher$$anonfun$compareMaps$1.appl
y(JsonBodyMatcher.scala:113)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221
)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:
428)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:
428)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compareMaps(JsonBodyMatcher
.scala:113)
        at au.com.dius.pact.matchers.JsonBodyMatcher.compare(JsonBodyMatcher.sca
la:44)
        at au.com.dius.pact.matchers.JsonBodyMatcher.matchBody(JsonBodyMatcher.s
cala:16)
        at au.com.dius.pact.model.Matching$.matchBody(Matching.scala:135)
        at au.com.dius.pact.model.ResponseMatching.responseMismatches(ResponseMa
tching.scala:19)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ResponseComparison.compareResponse(Response
Comparison.groovy:44)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:6
36)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ProviderVerifier.verifyRequestResponsePact(
ProviderVerifier.groovy:240)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:6
36)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ProviderVerifier.verifyResponseFromProvider
(ProviderVerifier.groovy:227)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:6
36)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ProviderVerifier.verifyInteraction(Provider
Verifier.groovy:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1073)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1372)
        at org.codehaus.groovy.runtime.dgm$149.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ProviderVerifier.forEachInteraction(Provide
rVerifier.groovy:74)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:6
36)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterf
ace.java:215)
        at au.com.dius.pact.provider.ProviderVerifier.runVerificationForConsumer
(ProviderVerifier.groovy:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1073)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMe
thods.java:1372)
        at org.codehaus.groovy.runtime.dgm$149.doMethodInvoke(Unknown Source)
        at au.com.dius.pact.provider.ProviderVerifier.verifyProvider(ProviderVer
ifier.groovy:42)
        at au.com.dius.pact.provider.gradle.PactVerificationTask.verifyPact(Pact
VerificationTask.groovy:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:589)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:572)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
e(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
ter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)

Failures:

0) Verifying a pact between ds_consumer_retail and DataServiceProvider - a retri
eve a Data Service request Given Scenario of Retail Site is retrieving data from
Data Service
      head of empty list

:pactVerify_DataServiceProvider FAILED

FAILURE: Build failed with an exception.

**Comment by uglyog** [comment]
released as part of 3.1.0
