### ISSUE TITLE
Receiving error message 'java.io.IOException: Was not able load pacts from broker' when using @PactBroker in pact-jvm-provider-junit 

### ISSUE THREAD

**Issue by GeorgeSimon** [DiUS/pact-jvm#196]
I pulled built the pact-jvm repo this afternoon so that I could use the @PactBroker annotation.

Here's my test:

@RunWith(PactRunner.class)
@Provider("CardServiceProvider")
@PactBroker(host="uscinwsdfyv4xq1", port=80)
public class PactVerifyTest {
    @TestTarget // Annotation denotes Target that will be used for tests
    public final Target target = new HttpTarget(8080);
}

And here's the error:

java.io.IOException: Was not able load pacts from broker

	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:59)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:43)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.http.impl.conn.PoolingHttpClientConnectionManager.setValidateAfterInactivity(I)V
	at com.github.rholder.retry.Retryer$ExceptionAttempt.<init>(Retryer.java:184)
	at com.github.rholder.retry.Retryer.call(Retryer.java:113)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:55)
	... 14 more
Caused by: java.lang.NoSuchMethodError: org.apache.http.impl.conn.PoolingHttpClientConnectionManager.setValidateAfterInactivity(I)V
	at org.apache.http.client.fluent.Executor.<clinit>(Executor.java:99)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.lambda$load$3(PactBrokerLoader.java:57)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader$$Lambda$7/752316209.call(Unknown Source)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:110)
	... 15 more

Disconnected from the target VM, address: '127.0.0.1:50514', transport: 'socket'

Process finished with exit code -1

I know it's building the URI to the Pact Broker properly because I can see the string as I step through the code and it builds a URI that I'm able to successfully reach through Chrome and Postman.

Any suggestions?
Thanks

**Comment by GeorgeSimon** [comment]
Here's the URI it builds:
http://uscinwsdfyv4xq1/pacts/provider/CardServiceProvider/latest

Hand the response when I access it in Chrome:

{"_links":{"self":{"href":"http://uscinwsdfyv4xq1/pacts/provider/CardServiceProvider/latest","title":"Latest pact versions for the provider CardServiceProvider"},"provider":{"href":"http://uscinwsdfyv4xq1/pacticipants/CardServiceProvider","title":"CardServiceProvider"},"pacts":[{"href":"http://uscinwsdfyv4xq1/pacts/provider/CardServiceProvider/consumer/HouseholdConsumer/version/1.0.0","title":"Pact between HouseholdConsumer (v1.0.0) and CardServiceProvider","name":"HouseholdConsumer"}]}}

**Comment by GeorgeSimon** [comment]
I found the problem, but I'm not sure why it occurs...

pact-jvm-provider-junit_2.11:3.2.1 uses the org.apache.httpcomponents:httpclient:4.5 library. However, when I build the project, it pulls in version 4.3.6, not 4.5.

I got around the problem by doing the following steps:

1. remove pact-jvm-provider-junit_2.11:3.2.1 from the dependencies section of my POM file. Build the project with the 'clean' goal to make sure pact-jvm-provider-junit_2.11 and all of its dependencies are removed.

2. add the following blocks to my project's POM file:
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>fluent-hc</artifactId>
            <version>4.5</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5</version>
            <scope>compile</scope>
        </dependency>

Rebuild my project to make sure version 4.5 of the org.apache.httpcomponents:httpclient library is pulled in.

3. add pact-jvm-provider-junit_2.11:3.2.1 back to the dependencies section of my POM file, and rebuild.

This allows me to run the pact verify tests. But it leaves my project in an undesired state. When I look at my project's list of external libraries I see both version (4.3.6 and 4.5) of org.apache.httpcomponents:httpclient. However, when I look at the list of Maven projects I only see version 4.5. (I'm using IntelliJ.)

**Comment by uglyog** [comment]
It should be using 4.5. I'll try to see what is pulling in 4.3.6 and clean that up.

**Comment by uglyog** [comment]
I've gone through all the projects and can't see where the 4.3.6 version is coming from. It must be a transitive dependency that maven is incorrectly bringing in. 

Could you run `maven dependency:tree` on your project? Also, can you provide the version of maven you are using.

**Comment by GeorgeSimon** [comment]
I won't have access to my workstation at work until Monday. I'll run the maven dependency:tree, check the version and report back as soon as I get access.
