### ISSUE TITLE
How to verify custom pact with provider

### ISSUE THREAD

**Issue by anurag0249** [DiUS/pact-jvm#250]
## I have produced "test_consumer-test_provider.json" by executed test ExampleJavaConsumerPactTest. But when I am trying to verify same "test_consumer-test_provider.json" file provider by placing this file into "pact-jvm\pact-jvm-provider-junit\src\test\resources\pacts" and writing a test class CustomeConsumerPactTest.class as below

package au.com.dius.pact.provider.junit;
import....
@RunWith(PactRunner.class)
@Provider("test_provider")
@PactFolder("pacts")
public class CustomeConsumerPactTest  {
    private static final Logger LOGGER = LoggerFactory.getLogger(CustomeConsumerPactTest.class);

   @ClassRule
    public static final ClientDriverRule embeddedService = new ClientDriverRule(8332);

```
@BeforeClass
public static void setUpService() {
    //Run DB, create schema
    //Run service
    //...
}

@Before
public void before() {
    // Rest data
    // Mock dependent service responses
    // ...
    embeddedService.addExpectation(
            onRequestTo("/second"), giveEmptyResponse()
    );
}

@State("default")
public void toDefaultState() {
    // Prepare service before interaction that require "default" state
    // ...
  LOGGER.info("Now service in default state");
}
@TargetRequestFilter
public void exampleRequestFilter(HttpRequest request) {
  LOGGER.info("exampleRequestFilter called: " + request);
}
@TestTarget
public final Target target = new HttpTarget(8332);
```
## }

Getting below errors :
com.github.restdriver.clientdriver.exception.ClientDriverFailedExpectationException: Unexpected request(s): [OPTIONS /second, GET /]
    at com.github.restdriver.clientdriver.jetty.DefaultClientDriverJettyHandler.checkForUnexpectedRequests(DefaultClientDriverJettyHandler.java:178)
    at com.github.restdriver.clientdriver.ClientDriver.verify(ClientDriver.java:130)
    at com.github.restdriver.clientdriver.ClientDriverRule$ClientDriverStatement.evaluate(ClientDriverRule.java:137)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Could you provide me steps/process how can I verify this custom pact file with provider.

Thanks in advance

**Comment by uglyog** [comment]
`ExampleJavaConsumerPactTest` defines two expectations, a GET request to `/` and an OPTIONS request to `/second`. These will be recorded in the pact file.

In `CustomeConsumerPactTest` you are using client driver as the provider, which is being set-up here:

```
    embeddedService.addExpectation(
            onRequestTo("/second"), giveEmptyResponse()
    );
```

So pact is going to make the following two requests (order may be different):

```
GET /
OPTIONS /second
```

while the client driver is expecting

```
GET /second
```

and is failing the test with `ClientDriverFailedExpectationException: Unexpected request(s): [OPTIONS /second, GET /]`

**Comment by anurag0249** [comment]
How client driver will support ?
OPTIONS /second

How to  define below code if response is not empty?
 embeddedService.addExpectation(
            onRequestTo("/second"), giveEmptyResponse()
    );

**Comment by uglyog** [comment]
I've never used client driver so I can't help, you'll need to read the documentation on that: https://github.com/rest-driver/rest-driver/wiki
