### ISSUE TITLE
Content-length in header cause Request Failed - null

### ISSUE THREAD

**Issue by b4456609** [DiUS/pact-jvm#255]
I use Jersey Client. It auto generates Content-Length in header. I found it cause error in provider test after lots of trying. When I remove Content-Length in json file, the test work.
But I found another issue is that I couldn't write java api to generate response headers. In my case, I need to manually add `"Content-Type": "application/json"` in response section.

```java
    @Override
    protected PactFragment createFragment(PactDslWithProvider builder) {
        Map<String, String> headers = new HashMap<String, String>();
        headers.put("Connection", "keep-alive");
        headers.put("Accept", "application/json");
        headers.put("Content-Type", "application/json");

        return builder.uponReceiving("a request for user")
                .path("/user/sync")
                .method("POST")
                .body(sendBody)
                .headers(headers)
                .matchHeader("Host", ".*", "localhost:34545")
                .matchHeader("User-Agent", ".*", "Jersey/2.22.1")
                .matchHeader("Content-Length", ".*", "628")
                .willRespondWith()
                .status(200)
                .body(sendBody).toFragment();
    }
```

```json
{
    "provider": {
        "name": "easylearn-user"
    },
    "consumer": {
        "name": "easylearn-mobile"
    },
    "interactions": [
        {
            "providerState": null,
            "description": "a request for user",
            "request": {
                "method": "POST",
                "path": "/user/sync",
                "headers": {
                    "Connection": "keep-alive",
                    "User-Agent": "Jersey/2.22.1",
                    "Host": "localhost:34545",
                    "Accept": "application/json",
                    "Content-Length": "628",
                    "Content-Type": "application/json"
                },
                "body": {
                    "folder": [
                        {
                            "id": "allPackId",
                            "name": "All",
                            "pack": [
                                "pack1460470093831",
                                "pack1460470104891"
                            ]
                        },
                        {
                            "id": "fjoeiwjowfe",
                            "name": "\u6211\u7684\u6700\u611b",
                            "pack": [
                                "pack1460470093831"
                            ]
                        },
                        {
                            "id": "allfolder",
                            "name": "\u5168\u90e8\u7684\u61f6\u4eba\u5305",
                            "pack": [
                                "pack1460470104891"
                            ]
                        }
                    ],
                    "setting": {
                        "last_sync_time": 1419519614000,
                        "mobile_network_sync": true,
                        "modified": false,
                        "version": 1,
                        "wifi_sync": true
                    },
                    "user": {
                        "id": "100000233589366",
                        "name": "\u904a\u5ba2"
                    }
                },
                "matchingRules": {
                    "$.headers.Content-Length": {
                        "regex": ".*"
                    },
                    "$.headers.User-Agent": {
                        "regex": ".*"
                    },
                    "$.headers.Host": {
                        "regex": ".*"
                    }
                }
            },
            "response": {
                "status": 200,
                "body": "{\n  \"user\": {\n    \"id\": \"100000233589366\",\n    \"name\": \"\u904a\u5ba2\"\n  },\n  \"setting\": {\n    \"wifi_sync\": true,\n    \"mobile_network_sync\": true,\n    \"version\": 1,\n    \"modified\": false,\n    \"last_sync_time\": 1419519614000\n  },\n  \"folder\": [\n    {\n      \"id\": \"allPackId\",\n      \"name\": \"All\",\n      \"pack\": [\n        \"pack1460470093831\",\n        \"pack1460470104891\"\n      ]\n    },\n    {\n      \"id\": \"fjoeiwjowfe\",\n      \"name\": \"\u6211\u7684\u6700\u611b\",\n      \"pack\": [\n        \"pack1460470093831\"\n      ]\n    },\n    {\n      \"id\": \"allfolder\",\n      \"name\": \"\u5168\u90e8\u7684\u61f6\u4eba\u5305\",\n      \"pack\": [\n        \"pack1460470104891\"\n      ]\n    }\n  ]\n}"
            }
        }
    ],
    "metadata": {
        "pact-specification": {
            "version": "2.0.0"
        },
        "pact-jvm": {
            "version": "3.2.7"
        }
    }
}
```
I use gradle to test provider
```
20:30:24.416 [QUIET] [system.out] 
20:30:24.416 [QUIET] [system.out] Verifying a pact between easylearn-user and easylearnMobile
20:30:24.418 [QUIET] [system.out]   [Using file /home/bernie/project/easylearn/easylearn-user/pact/a.json]
20:30:24.539 [QUIET] [system.out]   a request for user
20:30:24.542 [DEBUG] [au.com.dius.pact.provider.ProviderVerifier] Verifying via request/response
20:30:24.591 [DEBUG] [au.com.dius.pact.provider.ProviderClient] Making request for provider au.com.dius.pact.provider.ProviderInfo(http, 140.121.101.163, 7084, /, easylearnMobile, null, null, null, null, null, false, null, changeit, null, true, REQUST_RESPONSE, [], [au.com.dius.pact.provider.ConsumerInfo(easylearn-user, /home/bernie/project/easylearn/easylearn-user/pact/a.json, null, true, REQUST_RESPONSE, null, null)]):
20:30:24.592 [DEBUG] [au.com.dius.pact.provider.ProviderClient] 	method: POST
	path: /user/sync
	query: null
	headers: [Accept:application/json, Connection:keep-alive, Content-Length:628, Content-Type:application/json, Host:localhost:34545, User-Agent:Jersey/2.22.1]
	matchers: [$.headers.Content-Length:[regex:.*], $.headers.Host:[regex:.*], $.headers.User-Agent:[regex:.*]]
	body: {"folder":[{"id":"allPackId","name":"All","pack":["pack1460470093831","pack1460470104891"]},{"id":"fjoeiwjowfe","name":"\u6211\u7684\u6700\u611b","pack":["pack1460470093831"]},{"id":"allfolder","name":"\u5168\u90e8\u7684\u61f6\u4eba\u5305","pack":["pack1460470104891"]}],"setting":{"last_sync_time":1419519614000,"mobile_network_sync":true,"modified":false,"version":1,"wifi_sync":true},"user":{"id":"100000233589366","name":"\u904a\u5ba2"}}
20:30:24.784 [QUIET] [system.out]       Request Failed - null
20:30:24.787 [QUIET] [system.out] 
20:30:24.787 [QUIET] [system.out] Failures:
20:30:24.787 [QUIET] [system.out] 
20:30:24.792 [QUIET] [system.out] 0) Verifying a pact between easylearn-user and easylearnMobile - a request for user
20:30:24.794 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':pactVerify_easylearnMobile'
20:30:24.794 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :pactVerify_easylearnMobile FAILED
20:30:24.794 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :pactVerify_easylearnMobile (Thread[main,5,main]) completed. Took 0.416 secs.
20:30:24.794 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 2.458 secs, idle: 0.001 secs
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] 
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] 
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':pactVerify_easylearnMobile'.
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] > Cannot invoke method split() on null object
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] 
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
20:30:24.800 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
20:30:24.801 [LIFECYCLE] [org.gradle.BuildResultLogger] 
20:30:24.801 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
20:30:24.801 [LIFECYCLE] [org.gradle.BuildResultLogger] 
20:30:24.801 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 5.935 secs
```

**Comment by uglyog** [comment]
You can set the content type of the response body with a second parameter to the body method:

```java
          .body(sendBody, "application/json")
```

For the null pointer exception, could you run it again with `-Ppact.showStacktrace` and post the stack trace?

**Comment by uglyog** [comment]
BTW, I would not include the `Content-Length` header in the pact test, as it is set based on the size of the body and will change.

**Comment by b4456609** [comment]
Here is the output of the `gradle pactVerify -Ppact.showStacktrace`
```
gradle pactVerify -Ppact.showStacktrace
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:pactVerify_easylearnMobile

Verifying a pact between easylearn-user and easylearnMobile
  [Using file /home/bernie/project/easylearn/easylearn-user/pact/a.json]
  a request for user
      Request Failed - null
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderClient.makeRequest(ProviderClient.groovy:55)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.verifyResponseFromProvider(ProviderVerifier.groovy:240)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.verifyInteraction(ProviderVerifier.groovy:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1077)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1084)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.forEachInteraction(ProviderVerifier.groovy:73)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.runVerificationForConsumer(ProviderVerifier.groovy:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1077)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1084)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.ProviderVerifier.verifyProvider(ProviderVerifier.groovy:45)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at au.com.dius.pact.provider.gradle.PactVerificationTask.verifyPact(PactVerificationTask.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:96)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 124 more

Failures:

0) Verifying a pact between easylearn-user and easylearnMobile - a request for user
:pactVerify_easylearnMobile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pactVerify_easylearnMobile'.
> Cannot invoke method split() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.962 secs
```

**Comment by b4456609** [comment]
The consumer test failed on verification in header if I don't add Content-Length in the header.

**Comment by uglyog** [comment]
Pact will ignore headers that you don't specify in your test. You should only specify the things that are important for the interaction. I would leave out `Connection`, `Host`, `User-Agent` and `Content-Length`.

**Comment by uglyog** [comment]
A workable example would be:

```java
    @Override
    protected PactFragment createFragment(PactDslWithProvider builder) {
        return builder.uponReceiving("a request for user")
                .path("/user/sync")
                .method("POST")
                .body(sendBody, "application/json")
                .willRespondWith()
                .status(200)
                .body(sendBody, "application/json").toFragment();
    }
```

**Comment by b4456609** [comment]
It works. I change code to `.body(sendBody, "application/json")`.
Thank you!

**Comment by tl-madhulika-mitra** [comment]
@uglyog - We use Wiremock pact generator to generate our pact and the header content-length auto generates. And when we try to test the provider side, the test fails with 408. We are using a Pact Broker to test, so cannot remove headers at runtime(not sure if there exists a way). Imagining this thread is quite old, is there a way to work around this.

PS: Test works completely fine, without this header
