### ISSUE TITLE
Cannot get property 'templated' on null object

### ISSUE THREAD

**Issue by RodrigoBerto** [DiUS/pact-jvm#257]
Hi, I'm trying to run my pact provider tests against the pact broker using au.com.dius:pact-jvm-provider-maven_2.11 but it returns the following error message:

`Execution default-cli of goal au.com.dius:pact-jvm-provider-maven_2.11:3.2.6:verify failed: Cannot get property 'templated' on null object`

The following is the full stacktrace that it shows:

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal au.com.dius:pact-jvm-provider-maven_2.11:3.2.6:verify failed: Cannot get property 'templated' on null object
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.NullPointerException: Cannot get property 'templated' on null object
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.broker.HalClient.fetchLink(HalClient.groovy:54)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.broker.HalClient.navigate(HalClient.groovy:48)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.broker.PactBrokerClient.fetchConsumers(PactBrokerClient.groovy:24)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.ProviderInfo.hasPactsFromPactBroker(ProviderInfo.groovy:61)
    at au.com.dius.pact.provider.ProviderInfo.hasPactsFromPactBroker(ProviderInfo.groovy)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.maven.PactProviderMojo$_execute_closure6.doCall(PactProviderMojo.groovy:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    at groovy.lang.Closure.call(Closure.java:426)
    at groovy.lang.Closure.call(Closure.java:442)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
    at org.codehaus.groovy.runtime.dgm$162.doMethodInvoke(Unknown Source)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
    at au.com.dius.pact.provider.maven.PactProviderMojo.execute(PactProviderMojo.groovy:46)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    ... 20 more
```

Do you have any idea what could be wrong here?It's coming from https://github.com/DiUS/pact-jvm/blob/bedae45f3701c8fe546f6817d6f5a3af29b75766/pact-jvm-provider/src/main/groovy/au/com/dius/pact/provider/broker/HalClient.groovy

I have configured my build as it describes in https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#verifying-pact-files-from-a-pact-broker-version-311231

Thanks.

**Comment by uglyog** [comment]
Looks like the pact broker is not returning something that the plugin is expecting. I'll dig a bit deeper to see what is going on.

**Comment by RodrigoBerto** [comment]
No worries. I decided to use the JUnit runner and got it working properly, but wasn't able to run the provider tests using the broker pact file with the maven plugin.

So, here is a question regarding the usage of system properties in @Provider and @PactURL annotations. Is it possible to pass a system property as @Provider("${provider.name}")? I tried using it as it the documentation says with @PactBroker but seems to fail.

Cheers

**Comment by uglyog** [comment]
Only the @PactBroker annotation works with system properties

**Comment by uglyog** [comment]
It looks like failure is due to the pact broker not returning any links to the latest pacts for the provider. I'm going to test this against an empty broker.

**Comment by uglyog** [comment]
Can you run maven with the -X option. I'm looking for the lines that start with:
```
[DEBUG] Fetching: /
```

**Comment by uglyog** [comment]
From what I can work out, that error arises when the response is not a valid HAL response. Can you check that the URL to the pact broker is not mis-configured?

If you access the pact broker URL directly with a REST client, or curl, you should see a response like the following:

```console
$ curl -v http://pact-broker/
*   Trying 127.0.0.1...
* Connected to pact-broker (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: pact-broker
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/hal+json
< Content-Length: 615
< Connection: keep-alive
< Status: 200 OK
< Date: Sat, 28 May 2016 05:39:20 GMT
< Server: Webmachine-Ruby/1.4.0 Rack/1.3
< X-Powered-By: Phusion Passenger 4.0.58
< 
* Connection #0 to host pact-broker left intact
{"_links":{"self":{"href":"http://pact-broker","title":"Index","templated":false},"pb:latest-pact-versions":{"href":"http://pact-broker/pacts/latest","title":"Latest pact versions","templated":false},"pb:pacticipants":{"href":"http://pact-broker/pacticipants","title":"Pacticipants","templated":false},"pb:latest-provider-pacts":{"href":"http://pact-broker/pacts/provider/{provider}/latest","title":"Latest pacts by provider","templated":true},"pb:webhooks":{"href":"http://pact-broker/webhooks","title":"Webhooks","templated":false},"curies":[{"name":"pb","href":"http://pact-broker/doc/{rel}","templated":true}]}}
```

I'm going to add a more appropriate error message if the response is not a valid HAL response.
