### ISSUE TITLE
ContractTest.java JUnit test is failing

### ISSUE THREAD

**Issue by csikosbalint** [DiUS/pact-jvm#262]
Hi,

I have put the au.com.dius.pact.provider.junit.ContractTest.java from the test to my maven project and also the test/resources/pacts folder content. I receive the error below. Can anybody help? Thank you!

```
java.lang.NoSuchMethodError: au.com.dius.pact.model.Interaction.getProviderState()Ljava/lang/String;

	at au.com.dius.pact.provider.junit.InteractionRunner.withStateChanges(InteractionRunner.java:194)
	at au.com.dius.pact.provider.junit.InteractionRunner.interactionBlock(InteractionRunner.java:186)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:143)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:100)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.github.restdriver.clientdriver.ClientDriverRule$Clijava.lang.NoSuchMethodError: au.com.dius.pact.model.Interaction.getProviderState()Ljava/lang/String;

	at au.com.dius.pact.provider.junit.InteractionRunner.withStateChanges(InteractionRunner.java:194)
	at au.com.dius.pact.provider.junit.InteractionRunner.interactionBlock(InteractionRunner.java:186)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:143)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:100)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.github.restdriver.clientdriver.ClientDriverRule$ClientDriverStatement.evaluate(ClientDriverRule.java:171)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

entDriverStatement.evaluate(ClientDriverRule.java:171)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


```

**Comment by uglyog** [comment]
Looks like there is a method missing on the interface. I'll fix that.

**Comment by uglyog** [comment]
What version of the library are you using?

**Comment by csikosbalint** [comment]
```
Thanks for the question about the versions. I did a maven project where I wanted to test both consumer and producer (document walkthrough). I included both dependencies 

       <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-consumer-junit_2.11</artifactId>
            <version>RELEASE</version>
        </dependency>

        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-junit_2.10</artifactId>
            <version>RELEASE</version>
        </dependency>

This cause multiple versions of the model:
Maven: au.com.dius:pact-jvm-model_2.10:2.4.9
Maven: au.com.dius:pact-jvm-model_2.11:3.2.7

This set up caused the test run error see above.

RESOLUTION:
removing consumer dependency will leave only one model dependencies.
Maven: au.com.dius:pact-jvm-model_2.10:2.4.9
Now the test run green.
```

**Comment by csikosbalint** [comment]
Maven handles the transient dependencies when I use 2.11 for both consumer and producer. It was my fault. I think we can close this issue, thanks for your help!
