### ISSUE TITLE
Could not initialize class au.com.dius.pact.model.PactReader

### ISSUE THREAD

**Issue by BenSayers** [DiUS/pact-jvm#365]
I am using pact-jvm-provider-junit_2.11.

When I use version 2.2.11 my tests pass.

When I use versions 3.2.12 to 3.3.3 my provider tests fail with the following exception:
```
java.lang.NoClassDefFoundError: Could not initialize class au.com.dius.pact.model.PactReader
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.java:123)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:78)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

When I use version 3.3.4 I get a different exception:
```
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.createMap(ScriptBytecodeAdapter.java:623)
	at au.com.dius.pact.provider.broker.PactBrokerClient.<init>(PactBrokerClient.groovy)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.newPactBrokerClient(PactBrokerLoader.java:105)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.java:77)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:61)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.java:73)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Here is my test class
```java
package com.example;

import au.com.dius.pact.provider.junit.PactRunner;
import au.com.dius.pact.provider.junit.Provider;
import au.com.dius.pact.provider.junit.State;
import au.com.dius.pact.provider.junit.loader.PactBroker;
import au.com.dius.pact.provider.junit.target.HttpTarget;
import au.com.dius.pact.provider.junit.target.Target;
import au.com.dius.pact.provider.junit.target.TestTarget;
import com.example.UserRepository;
import com.example.User;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.boot.test.WebIntegrationTest;
import org.springframework.test.context.TestContextManager;

@SpringApplicationConfiguration(Application.class)
@WebIntegrationTest
@RunWith(PactRunner.class)
@Provider("user-service")
@PactBroker(protocol = "https", host = "my-pact-broker.com", port = "443")
public class ContractTest {
    @Autowired
    UserRepository userRepository;

    private static final TestContextManager manager = new TestContextManager(ContractTest.class);

    @BeforeClass
    public static void beforeAll() throws Exception {
        manager.beforeTestClass();
    }

    @Before
    public void beforeEach() throws Exception {
        manager.beforeTestMethod(this, this.getClass().getMethod("beforeEach"));
        manager.prepareTestInstance(this);

        userRepository.deleteAll();
    }

    @State("there is one user in the database")
    public void thereIsOneUserInTheDatabase() {
        User user2 = new User().setUserId(2).setFirstName("Bob").setLastName("Smith").setEmail("bsmith@domain.com");
        userRepository.add(1, user2);
    }

    @State("the user service is down")
    public void theUserServiceIsDown() {
        User dodgyUser = new User() {
            @Override
            public int getUserId() {
                throw new RuntimeException("Dodgy user exception");
            }
        };
        userRepository.add(1, dodgyUser);
    }

    @After
    public void afterEach() throws Exception {
        manager.afterTestMethod(this, this.getClass().getMethod("beforeEach"), null);
    }

    @AfterClass
    public static void afterAll() throws Exception {
        manager.afterTestClass();
    }

    @TestTarget
    public final Target target = new HttpTarget(8081);
}
```

**Comment by uglyog** [comment]
Looks like you might be missing some dependencies, possibly the groovy one. There should be a additional cause exception stacktrace to those you provided.

Are you using a build framework like Gradle or Maven, or are you running the test from the IDE?

**Comment by BenSayers** [comment]
We had a dodgy maven mirror. Closing this as its not your bug!
