### ISSUE TITLE
ERROR casting map to au.com.dius.pact.model.Provider when initializing

### ISSUE THREAD

**Issue by Cramsden** [DiUS/pact-jvm#448]
We are trying to set up our contact tests using the contact created by our iOS application and following the BooksPactProviderTest example. When we run the tests we get the following error:

`
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Error casting map to au.com.dius.pact.model.Provider, Reason: null
                 at org.codehaus.groovy.runtime.DefaultGroovyMethods.asType(DefaultGroovyMethods.java:10732)
                at org.codehaus.groovy.runtime.dgm$53.doMethodInvoke(Unknown Source)
                at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
                at au.com.dius.pact.model.PactReader.loadV2Pact(PactReader.groovy:66)
                at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
                at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy:40)
                at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy)
                at au.com.dius.pact.provider.junit.loader.PactFolderLoader.load(PactFolderLoader.java:54)
                at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.java:73)
                at au.com.dius.pact.provider.junit.RestPactRunner.<init>(RestPactRunner.java:14)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
                at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:98)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
                at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
                at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

When we step through and try to debug our issue we find that the failure happens  when trying to convert our provider json object as a map 

`"provider" : {
      "name": "test-name"
  }`

with the error:
`org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{name=Seeds-Endpoint}' with class 'groovy.json.internal.LazyMap' to class 'au.com.dius.pact.model.Provider' due to: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: name for class: au.com.dius.pact.model.Provider`

**Comment by uglyog** [comment]
Could you provide the version of pact-jvm and the build tool (Gradle/Maven, etc.) you are using?

**Comment by Cramsden** [comment]
The build tool we are using is Maven, and the version of pact-jvm is 2.1.13

**Comment by Cramsden** [comment]
Should we additionally be pulling in pact-jvm?

**Comment by uglyog** [comment]
No, I just wanted to confirm the version. That is the latest.

**Comment by uglyog** [comment]
I have no idea why you are getting `ReadOnlyPropertyException: Cannot set readonly property: name for class: au.com.dius.pact.model.Provider` because the name property is not read only. But I have added a fix that might sort out your issue.

**Comment by uglyog** [comment]
Fix released with version 3.4.1
