### ISSUE TITLE
AmqpTarget fails to get class name of methods annotated with @PactVerifyProvider annotation when method name has spaces in Kotlin

### ISSUE THREAD

**Issue by shyamz-22** [DiUS/pact-jvm#515]
When trying to verify a message pact with __au.com.dius:pact-jvm-provider-junit_2.11:3.4.1__ 
I get `String index out of range` error: 

The error occurs in `org.reflections:reflections:0.9.10, Utils.java line no: 67`

```java
 String className = memberKey.substring(memberKey.lastIndexOf(' ') + 1, p1);
```
<pre>
0) a message with A type
String index out of range: -18
java.lang.AssertionError: 
0 - String index out of range: -18

at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:86)
at au.com.dius.pact.provider.junit.target.AmqpTarget.testInteraction(AmqpTarget.java:58)
at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:181)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:141)
at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:105)
at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:51)
</pre>

__Sample Kotlin Code__
```kotlin
@RunWith(PactRunner::class)
@Provider("test-provider")
@Consumer("test-consumer")
@PactFolder("pacts")
class PactProviderForMessagingTest {

    @JvmField
    @TestTarget
    val target: Target = AmqpTarget(Collections.singletonList("com.ennovate.pact.*"))

    @PactVerifyProvider("a message with A type")
    fun `verifyMessage - has A`(): String {

        val message = Message(type = "A")
        return jacksonObjectMapper().writeValueAsString(message)
    }

    @PactVerifyProvider("a message with B type")
    fun `verifyMessage - has B`(): String {

        val message = Message(type = "B")
        return jacksonObjectMapper().writeValueAsString(message)
    }

    @State("on type A",
            "on type B")
    fun doNothing(): Unit {}

}
```

**Comment by uglyog** [comment]
I have raised an issue with the reflections project.
