### ISSUE TITLE
Error when testing string body with spring pact

### ISSUE THREAD

**Issue by Nalha** [DiUS/pact-jvm#517]
After updating a consumer test to 3.5.3 the providers test started throwing a body mismatch exception, after updating it to 3.5.3 it throws the following exception:

```
java.lang.AssertionError: 
0 - au.com.dius.pact.model.matchingrules.TypeMatcher cannot be cast to au.com.dius.pact.model.matchingrules.RegexMatcher

        at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:86)
        at au.com.dius.pact.provider.spring.target.MockMvcTarget.testInteraction(MockMvcTarget.java:105)
        at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:196)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:156)
        at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:114)
        at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:52)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

And it's when testing a body with a string type:

```
                .willRespondWith()
                    .status(200)
                    .body(PactDslJsonRootValue.stringType())
```
Pact JSON:
```
                "body": "\"string\"",
                "matchingRules": {
                    "body": {
                        "$": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
```

**Comment by bbarke** [comment]
What is the content type?

I worry this broke as a result of #491

This spec test appears to reproduce the error
```
{
  "match": true,
  "comment": "Plain string type matcher",
  "expected" : {
    "headers": { "Content-Type": "text/plain" },
    "body": "\"alligator named mary\"",
    "matchingRules": {
      "body": {
        "$": {
          "matchers": [
            {
              "match": "type"
            }
          ],
          "combine": "AND"
        }
      }
    }
  },
  "actual": {
    "headers": { "Content-Type": "text/plain" },
    "body": "\"Some String\""
  }
}
```

If this is the case, should a regex matcher be used instead? Since text/plain, by default, is a type of 'String'?

Changing the content type to `application/json` passes

**Comment by Nalha** [comment]
Yea it's defaulted to text/plain.

**Comment by Nalha** [comment]
I realised that the spring api returns a string without quotation marks, not sure thats even supposed to be supported here.

For anyone with a similar issue, I can recommend wrapping the string with JSONObject.quote(yourString);

**Comment by uglyog** [comment]
I'm re-opening this as there is an actual issue in that only a regex matcher can be used with `text/plain` bodies.

**Comment by ausarb** [comment]
I've been spinning my wheels for hours until I came upon this post.  We were returning json but the Content-Type was text/html and because of that, the producer pact runner wasn't using the matchers.  It was doing a direct text comparison on the body.    Not the exact problem as here but close enough that the comments here set me straight.  Thanks!
