### ISSUE TITLE
DateGenerator and TimeGenerator unable to handle format with timezone

### ISSUE THREAD

**Issue by a-ster** [DiUS/pact-jvm#523]
Using timestamp format with timezone, i.e. timestamp("dateTime", "yyyy-MM-dd'T'HH:mm:ssZ"), results in the following exception:

`java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
	at java.time.LocalDate.get0(LocalDate.java:680)
	at java.time.LocalDate.getLong(LocalDate.java:659)
	at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3335)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at java.time.LocalDateTime.format(LocalDateTime.java:1752)
	at au.com.dius.pact.model.generators.DateTimeGenerator.generate(Generator.kt:224)
	at au.com.dius.pact.model.generators.JsonContentTypeHandler$applyKey$1.invoke(Generators.kt:44)
	at au.com.dius.pact.model.generators.JsonContentTypeHandler$applyKey$1.invoke(Generators.kt:32)
	at au.com.dius.pact.model.generators.JsonContentTypeHandler.queryObjectGraph(Generators.kt:99)
	at au.com.dius.pact.model.generators.JsonContentTypeHandler.applyKey(Generators.kt:41)
	at au.com.dius.pact.model.generators.Generators$processBody$1$1.invoke(Generators.kt:206)
	at au.com.dius.pact.model.generators.Generators$processBody$1$1.invoke(Generators.kt:104)
	at au.com.dius.pact.model.generators.Generators.applyGenerator(Generators.kt:184)
	at au.com.dius.pact.model.generators.Generators$processBody$1.invoke(Generators.kt:204)
	at au.com.dius.pact.model.generators.Generators$processBody$1.invoke(Generators.kt:104)
	at au.com.dius.pact.model.generators.JsonContentTypeHandler.processBody(Generators.kt:35)
	at au.com.dius.pact.model.generators.Generators.processBody(Generators.kt:203)
	at au.com.dius.pact.model.generators.Generators.applyBodyGenerators(Generators.kt:194)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.Response.generatedResponse(Response.groovy:54)
	at au.com.dius.pact.consumer.BaseMockServer.generatePactResponse(MockHttpServer.kt:101)`

Checked the exception and it is caused by using LocalDate and LocalTime in the Generator class. Work-around is to provide an example instead of letting the timestamp be generated.

**Comment by uglyog** [comment]
I've switched from `LocalDateTime` to `ZonedDateTime` which can handle the timezone.

**Comment by a-ster** [comment]
Thanks!

**Comment by brettcooper** [comment]
Any update on when this fix will be released?

**Comment by uglyog** [comment]
It is in any version 3.5.5+
