### ISSUE TITLE
cannot instantiate PactProviderRuleMk2

### ISSUE THREAD

**Issue by Notso** [DiUS/pact-jvm#604]
I am trying to follow the example [on the jvm-consumer-junit README](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit) using the Rule, but I am getting a noSuchMethodError upon instantiation. I get this error even when I run the simplest junit test to simply new the PactProviderRule object like
        `@Test
    public void testNewPactProvider() {
        PactProviderRuleMk2 provider = new PactProviderRuleMk2("test_provider", "localhost", 8080, this);
    }`

The stack is
```
java.lang.NoSuchMethodError: au.com.dius.pact.model.MockProviderConfig.httpConfig(Ljava/lang/String;ILau/com/dius/pact/model/PactSpecVersion;)Lau/com/dius/pact/model/MockProviderConfig;

	at au.com.dius.pact.consumer.BaseProviderRule.<init>(BaseProviderRule.java:32)
	at au.com.dius.pact.consumer.PactProviderRuleMk2.<init>(PactProviderRuleMk2.java:26)
	at au.com.dius.pact.consumer.PactProviderRuleMk2.<init>(PactProviderRuleMk2.java:37)
	at com.example.contract.rest.QuickJunitTest.testNewProvider(QuickJunitTest.java:12)
```

This happens for me in IntelliJ IDEA and when running the maven install.
Here is what I believe to be the relevant pieces from the maven config
```
 <properties>
		<pact-jvm.version>3.5.10</pact-jvm.version>
		<spring.boot.version>1.4.2.RELEASE</spring.boot.version>
		<cxf.version>3.1.8</cxf.version>
		<jackson.version>2.8.4</jackson.version>
	</properties>
```

	```
	<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer-junit_2.11</artifactId>
			<version>${pact-jvm.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
		    <artifactId>rest-assured</artifactId>
		    <version>3.0.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer_2.11</artifactId>
			<version>${pact-jvm.version}</version>
			<scope>test</scope>
		</dependency>
```

**Comment by Notso** [comment]
I have resolved this. I should be using the latest pact artifacts (i.e., the _2.12 ones: pact-jvm-consumer-junit_2.12 and pact-jvm-consumer_2.12) but I was using _2.11. Also, I had some swagger-request-validator dependencies that were in turn pulling in a old version (3.2.6) of the pact-jvm-model. Once I adjusted to use the _2.12 artifacts and removed the dependencies on swagger-request-validator, then the instantiation succeeded.
