### ISSUE TITLE
NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V with pact-jvm-provider-spring_2.12:3.5.12

### ISSUE THREAD

**Issue by gaurav517** [DiUS/pact-jvm#639]
I am getting following with pact-jvm-provider-spring_2.12:3.5.12:

```
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

    at au.com.dius.pact.model.StatusMismatch.<init>(Matching.scala:40)
    at au.com.dius.pact.model.Matching$.matchStatus(Matching.scala:174)
    at au.com.dius.pact.model.ResponseMatching.responseMismatches(ResponseMatching.scala:21)
    at au.com.dius.pact.provider.ResponseComparison.compareResponse(ResponseComparison.groovy:40)
    at au.com.dius.pact.provider.ProviderVerifier.verifyRequestResponsePact(ProviderVerifier.groovy:228)
    at au.com.dius.pact.provider.spring.MvcProviderVerifier.verifyResponseFromProvider(MvcProviderVerifier.kt:43)
```

**Comment by uglyog** [comment]
Can you check that you are using the same versions of all the pact-jvm modules (3.5.12), as well as the same Scala version (2.12).
