### ISSUE TITLE
Load pact from classpath

### ISSUE THREAD

**Issue by pkubowicz** [DiUS/pact-jvm#669]
I use pact-jvm-provider-junit_2.12:3.5.15. I would like to have something like `@PactFolder` or `@PactUrl` that is able to read from classpath.

I prefer to distribute my pact in a JAR, this way I can easily version it, publish locally and have it available offline from my build tool cache.

`@PactUrl(urls = {"classpath:my_pact.json"})` does not work:
```
Unable to load pact file from 'classpath:my_pact.json' as it is neither a json document, file, input stream, reader or an URL
java.lang.UnsupportedOperationException: Unable to load pact file from 'classpath:my_pact.json' as it is neither a json document, file, input stream, reader or an URL
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at au.com.dius.pact.model.PactReader.loadFile(PactReader.groovy:201)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy:25)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy)
	at au.com.dius.pact.provider.junit.loader.PactUrlLoader.lambda$load$0(PactUrlLoader.java:35)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at au.com.dius.pact.provider.junit.loader.PactUrlLoader.load(PactUrlLoader.java:39)
```

I have working code that handles classpath, which I can provide in a pull request.

**Comment by rholshausen** [comment]
Use `@PactFolder`, it will try load as a resource first. See [ContractTest](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/test/java/au/com/dius/pact/provider/junit/ContractTest.java) which loads the pacts from the class path.

**Comment by pkubowicz** [comment]
This works in `ContractTest` only by accident: because the folder is a physical folder on disk, not a folder inside a JAR file.

In my case, `PactFolderLoader.load()` tries to call `pactFolder.listFiles()` for an entry inside a JAR and gets null, so considers no pact files are present.

**Comment by rholshausen** [comment]
Ok, in that case, a PR would be appreciated.
