### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'mimeType' on null object when the body of actual response not match with the Pact response

### ISSUE THREAD

**Issue by minhdoan159** [DiUS/pact-jvm#679]
I am using pact-jvm-provider_2.12-3.5.16 with its dependencies.
I met the issue that when i compare the actual response with the response retrieved from interaction of Pact record as the code below:
pact = new File("pact.json")
	pact.setWritable(true)
	pact.write(new JsonBuilder(pactJson).toPrettyString())
	testConsumerPact = new PactReader().loadPact(pact)
	List<Interaction> interactions = testConsumerPact.getInteractions()
	Interaction interaction1 = interactions[0]
// response is a Response Object
// responseMap is the map converted from actual response, response 
result = new ResponseComparison().compareResponse(interaction1.getResponse(), responseMap, response.getStatusCode(), response.getHeadersField(), response.getResponseText())

The exception java.lang.NullPointerException: Cannot get property 'mimeType' on null object
with the stacktrace as:
at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	**at au.com.dius.pact.provider.ResponseComparison.compareBody(ResponseComparison.groovy:125)**
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.ResponseComparison.compareResponse(ResponseComparison.groovy:44)
	at au.com.dius.pact.provider.ResponseComparison$compareResponse.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at Script1521429258419.run(Script1521429258419.groovy:99)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:183)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:108)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:291)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:282)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:261)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:253)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:201)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:74)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at TempTestCase1525926542020.run(TempTestCase1525926542020.groovy:21)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:653)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
I see that if my actual response have info same with the response retrieved from Pact., there is not exception and this lol passed, i could check the result.get("headers") or result.get("body") afterwards.
I think the compareBody or compareHeader method should not throw the exception althought the contents in the headers or bodies are different, even null, it should be added to the result with the failure reason instead.
Whether i got a mistake when using the pact-jvm-provider or it needs to be improved.
Please help to show me the solution!

**Comment by uglyog** [comment]
The `responseMap` needs to have the content type set for this code to work. Have a look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/src/test/groovy/au/com/dius/pact/provider/gradle/ResponseComparisonTest.groovy

**Comment by minhdoan159** [comment]
Thanks so much, it works!
