### ISSUE TITLE
WillResondWith().status(403) -> Test fails

### ISSUE THREAD

**Issue by vegetto313** [DiUS/pact-jvm#686]
Hi,

im trying to create a Pact with returncode 403 if a specific URL is called  (minimal version):

	@Pact(provider = PROVIDER_NAME, consumer = CONSUMER_NAME)
	public RequestResponsePact createPact(PactDslWithProvider builder) {
		return builder
				.uponReceiving(
						"A request with no permission")
				.path(REQUEST_URL_NO_PERMISSION)
				.method("GET")
				.willRespondWith()
				.status(403)
				.body("").toPact();
	}

	@Test
	@PactVerification(PROVIDER_NAME)
	public void runTest() throws IOException {
		Map<String, String> cc2 = new ConsumerClient(mockProvider.getUrl())
				.getAsMap(REQUEST_URL_NO_PERMISSION, null);
	};

If I run the JUnit Test, i get the following Exception:
java.lang.AssertionError: Pact Test function failed with an exception, possibly due to ExpectedButNotReceived(expectedRequests=[	method: GET
	path: /mypath
	query: [:]
	headers: [:]
	matchers: MatchingRules(rules=[path:Category(name=path, matchingRules={})])
	generators: Generators(categories={})
	body: OptionalBody(state=MISSING, value=null)])
	at au.com.dius.pact.consumer.BaseProviderRule.validateResult(BaseProviderRule.java:164)
	at au.com.dius.pact.consumer.BaseProviderRule$1.evaluate(BaseProviderRule.java:80)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
**Caused by: org.apache.http.client.HttpResponseException: Forbidden**
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:69)
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
	at org.apache.http.client.fluent.Response.returnContent(Response.java:97)

If i change 
				.willRespondWith()
				.status(403)
to for example
				.willRespondWith()
				.status(201)

the Test passes and the Pact-File is created.

Is there a way, to tell the Mock-Server to resond with a 403 statuscode, when a specific Url is called?

Thanks in Advance :)

**Comment by gopinath-langote** [comment]
Hello @vegetto313 ,

Here Pact is not the problem. Actually, the pact is responding status `403` but your test is failing because of the 403 exceptions.

Can you try,

```
@Test
@PactVerification(PROVIDER_NAME)
public void runTest() throws IOException {
        try {
	    Map<String, String> cc2 = new ConsumerClient(mockProvider.getUrl())
			.getAsMap(REQUEST_URL_NO_PERMISSION, null);
       } catch (Exception ignored){
      }
};
```


This might solve your problem.

**Comment by vegetto313** [comment]
Hi gopinath-langote,

this solved the Problem, thank you.

But this solutions seems like a workaround - at least to me with my little experience :)
In the end I have to try/catch every test I write to make it "green" and create a Pact, because the apache httpclient constantly throws Exceptions in different circumstances  (all 4XX Http Codes as it seems, in addition it happened in a different use-case which i don't remember exactly).

But nevertheless, thank you for your help ;)

**Comment by gopinath-langote** [comment]
Hello @vegetto313 ,

You are welcome.

But this solution seems like a workaround =>
>>>
For me, it's not the workaround, As your client is throwing an exception which pact cannot handle (or which is not in pact's control).

But good to have a conversation in the slack wider group so that we can get more views.


Thanks 😄

**Comment by rholshausen** [comment]
I concur with @gopinath-langote, Pact is behaving correctly. From Pact's point if view: It is executing test code, returning a 403 response as requested and the test code is throwing an exception. It can only conclude that the test has failed.
