### ISSUE TITLE
Pact ANNOTATED_METHOD verification throws error Verification Failed - No signature of method: 

### ISSUE THREAD

**Issue by kaushalye** [DiUS/pact-jvm#739]
Im trying to get the pact provider side working with
`<verificationType>ANNOTATED_METHOD</verificationType> `

Following the example in the above reference, I defined the .groovy file as follows  (ignore the simple return type), which get compiled to .class in the test classpath
`class VehicleTxnResourcePactTest {
  @PactVerifyProvider('a processed transaction')
  String verifyTransaction() {
   JsonOutput.toJson("some string")
 }
}`

However I am getting the following complaint
`Verifying a pact between MIRB and IPS - a processed transaction  Given transactions are processed
      No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public java.lang.String net.nxbos.ips.vehicletxn.resource.VehicleTxnResourcePactTest.verifyTransaction()]
      Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)`

Thanks in advance.

stack trace
`Verifying a pact between MIRB and IPS
  [Using File /Users/malinda/Code/ips-microservice-vehicle-txn/src/test/resources/pacts/MIRB-IPS.json]
  Given transactions are processed
         WARNING: State Change ignored as there is no stateChange URL
  a processed transaction
      Verification Failed - No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public java.lang.String net.nxbos.ips.vehicletxn.resource.VehicleTxnResourcePactTest.verifyTransaction()]
Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)
groovy.lang.MissingMethodException: No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public java.lang.String net.nxbos.ips.vehicletxn.resource.VehicleTxnResourcePactTest.verifyTransaction()]
Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.ProviderVerifier$_verifyResponseByInvokingProviderMethods_closure28.doCall(ProviderVerifier.groovy:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2078)
	at org.codehaus.groovy.runtime.dgm$165.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.ProviderVerifier.verifyResponseByInvokingProviderMethods(ProviderVerifier.groovy:323)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.ProviderVerifier.verifyInteraction(ProviderVerifier.groovy:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1087)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3202)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3172)
	at au.com.dius.pact.provider.ProviderVerifier.runVerificationForConsumer(ProviderVerifier.groovy:85)
	at au.com.dius.pact.provider.ProviderVerifier.runVerificationForConsumer(ProviderVerifier.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1087)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
	at org.codehaus.groovy.runtime.dgm$163.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.ProviderVerifier.verifyProvider(ProviderVerifier.groovy:61)
	at au.com.dius.pact.provider.maven.PactProviderMojo.execute(PactProviderMojo.kt:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Skipping publishing of verification results as it has been disabled (pact.verifier.publishResults is not 'true')

Failures:

0) Verifying a pact between MIRB and IPS - a processed transaction  Given transactions are processed
      No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public java.lang.String net.nxbos.ips.vehicletxn.resource.VehicleTxnResourcePactTest.verifyTransaction()]
      Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)
`

**Comment by kaushalye** [comment]
The class file
`import au.com.dius.pact.provider.PactVerifyProvider;
import groovy.json.JsonOutput;
import groovy.lang.GroovyObject;
import groovy.lang.MetaClass;
import org.codehaus.groovy.runtime.callsite.CallSite;
import org.codehaus.groovy.runtime.typehandling.ShortTypeHandling;

public class VehicleTxnResourcePactTest implements GroovyObject {
  public VehicleTxnResourcePactTest() {
    CallSite[] var1 = $getCallSiteArray();
    MetaClass var2 = this.$getStaticMetaClass();
    this.metaClass = var2;
  }

  @PactVerifyProvider("a processed transaction")
  public String verifyTransaction() {
    CallSite[] var1 = $getCallSiteArray();
    var1[0].callCurrent(this, "invoking verifyTransaction --------------");
    return (String)ShortTypeHandling.castToString(var1[1].call(JsonOutput.class, "some string"));
  }
}`

**Comment by jmtroconis-stratio** [comment]
Hi,

I'm having the same problem while verifying the pact on the producer side.

Consumer side test:
```
public class SaveInventoryConsumerTest {

    @Rule
    public PactProviderRuleMk2 mockProvider = new PactProviderRuleMk2("hello-world-provider",
        PactSpecVersion.V3, this);
    private RestTemplate restTemplate = new RestTemplate();

    @Pact(provider = "hello-world-provider", consumer = "hello-world-consumer")
    public RequestResponsePact createPact(PactDslWithProvider builder) {
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", MediaType.APPLICATION_JSON_UTF8_VALUE);


        PactDslJsonBody bodyResponse = new PactDslJsonBody()
            .stringValue("productName", "TV")
            .stringType("locationName", "CHENNAI")
            .integerType("quantity", 100);

        return builder.given("create inventory").uponReceiving("a request to save inventory")
            .path("/api/inventory")
            .body(bodyResponse)
            .method(RequestMethod.POST.name())
            .willRespondWith()
            .headers(headers)
            .status(200).body(bodyResponse).toPact();
    }

    @Test
    @PactVerification
    public void testCreateInventoryConsumer() throws IOException {

        Inventory inventory=new Inventory("TV", "CHENNAI", 100);
        HttpHeaders headers=new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
        HttpEntity<Object> request=new HttpEntity<Object>(inventory, headers);
        ResponseEntity<String> responseEntity=restTemplate.postForEntity(mockProvider.getUrl()+"/api/inventory", request, String.class);
        assertEquals("TV", JsonPath.read(responseEntity.getBody(),"$.productName"));
        assertEquals("CHENNAI", JsonPath.read(responseEntity.getBody(),"$.locationName"));
        assertEquals((Integer)100, (Integer)JsonPath.read(responseEntity.getBody(),"$.quantity"));
    }
}
```

Producer side test:

```
public class InventoryProviderTest {
  @PactVerifyProvider("a request to save inventory")
  public Inventory messageProvider() throws  Exception {
	  return new Inventory("TV", "CHENNAI", 100);
  }
}
```

Error while verifying on producer side:

```
Verifying a pact between hello-world-consumer and hello-world-provider
  [from URL http://localhost:8500/pacts/provider/hello-world-provider/consumer/hello-world-consumer/version/0.0.1-SNAPSHOT]
  Given create inventory
         WARNING: State Change ignored as there is no stateChange URL
  a request to save inventory
      Verification Failed - No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public com.helloworldprovider.domain.Inventory com.helloworldprovider.pact.producer.InventoryProviderTest.messageProvider() throws java.lang.Exception]
Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)

Failures:

0) Verifying a pact between hello-world-consumer and hello-world-provider - a request to save inventoryVerifying a pact between hello-world-consumer and hello-world-provider - a request to save inventory Given create inventory
      No signature of method: au.com.dius.pact.provider.ProviderVerifier.invokeProviderMethod() is applicable for argument types: (java.lang.reflect.Method) values: [public com.helloworldprovider.domain.Inventory com.helloworldprovider.pact.producer.InventoryProviderTest.messageProvider() throws java.lang.Exception]
      Possible solutions: invokeProviderMethod(java.lang.reflect.Method, java.lang.Object)
```
