### ISSUE TITLE
Having hostfile entries mapped to localhost can cause Pact tests to fail

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#742]
One of my co-workers was having issues running a Pact test failing on his box. The test ran fine on our build system and when other members of his team ran it. We discovered that he had an entry in his hostfile with a name matching one of the providers in our pactbroker that was mapped to localhost (hereafter hostfile_entry_with_pact). When the hostfile entry was removed, the test passed.

The failing test had a line where we were calling getUrl() on our instance of PactProviderRuleMk2. When we debugged in, we realized getUrl() was resolving to hostfile_entry_with_pact instead of the provider name we passed in when we newed up the pact provider rule.

I had him bump up to 3.5.19, and even more tests failed this time. The only test that did not fail was the one where the provider was hostfile_entry_with_pact. 

I also had him try a few other entries in his hostfile. A fake app name, my-app, mapped to localhost did not interfere with test runs, nor did other aliases for the project we were having issues with, like hostfile-entry-with-pact-ws, even though they're the same project in puppet. It's only when we use names matching the provider names as they are used in pact tests/the pact broker.

This is going to cause headaches anytime someone needs to do some feature work on a project that is in the broker.

Here's the stacktrace:

`java.lang.IllegalArgumentException: Host name may not be null
                at org.apache.http.util.Args.containsNoBlanks(Args.java:81)
                at org.apache.http.HttpHost.<init>(HttpHost.java:80)
                at org.apache.http.impl.execchain.MinimalClientExec.execute(MinimalClientExec.java:201)
                at org.apache.http.impl.client.MinimalHttpClient.doExecute(MinimalHttpClient.java:108)
                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
                at au.com.dius.pact.consumer.BaseMockServer.waitForServer(MockHttpServer.kt:206)
                at au.com.dius.pact.consumer.BaseMockServer.runAndWritePact(MockHttpServer.kt:169)
                at au.com.dius.pact.consumer.ConsumerPactRunnerKt.runConsumerTest(ConsumerPactRunner.kt:13)
                at au.com.dius.pact.consumer.BaseProviderRule.runPactTest(BaseProviderRule.java:152)
                at au.com.dius.pact.consumer.BaseProviderRule.access$100(BaseProviderRule.java:25)
                at au.com.dius.pact.consumer.BaseProviderRule$1.evaluate(BaseProviderRule.java:80)
                at org.junit.rules.RunRules.evaluate(RunRules.java:20)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
                at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)`

**Comment by LoraVolkert** [comment]
The previous version of pact that my co-worker was using was 3.5.12. Tests failed with that version too, but the behavior was slightly different and resulted in a different exception.

**Comment by uglyog** [comment]
Could you provide the test code line where you instantiate PactProviderRuleMk2, as well as the host file entries?

**Comment by LoraVolkert** [comment]
The provider in the failing test was originally instantiated like this:

`@Rule
    public PactProviderRuleMk2 provider = new PactProviderRuleMk2("prometheus-ws", this);`

and then updated to this:

`@Rule
    public PactProviderRuleMk2 provider = new PactProviderRuleMk2("prometheus-ws", PactSpecVersion.V3, this);`

It failed both ways.

Another test, the one with the provider matching the host file entry, has the provider instantiated like this:

`@Rule
    public PactProviderRuleMk2 provider = new PactProviderRuleMk2("raw_security_pricing_ws", PACT_TEST_SERVER, PACT_TEST_PORT, this);
`

The host file contained this entry near the middle:

`127.0.0.1 raw_security_pricing_ws`

**Comment by LoraVolkert** [comment]
News!

Another of my co-workers ran into this exact same problem, and I was able to diagnose the issue. He did not have this entry in his hostfile: 127.0.0.1	localhost

I think we can probably close this out?
