### ISSUE TITLE
NoClassDefFoundError: org/fusesource/jansi/AnsiConsole with pact-jvm-provider-maven 3.5.20

### ISSUE THREAD

**Issue by aricalee** [DiUS/pact-jvm#744]
Hi 

I'm running pact-jvm-provider-maven 3.5.20 with JDK 1.8.x 64bit in eclipse. When trying to run pact:verify, I got the following error

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:169)
	... 21 more
Caused by: java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiConsole
	at au.com.dius.pact.provider.maven.PactProviderMojo.execute(PactProviderMojo.kt:59)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

May I know if I missed anything here?

Thanks

**Comment by aricalee** [comment]
close this one as it has been resolved.
