### ISSUE TITLE
Message pact provider verification fails with JDK10 (AppClassLoader cannot be cast to URLClassLoader)

### ISSUE THREAD

**Issue by Bjoern-Hegstam** [DiUS/pact-jvm#767]
Hi, I'm trying to upgrade a project from Java 8 to 10 and encountered an error when running a message pact provider verification test.

I get the following error
```
Verification Failed - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
```

with stacktrace
```
java.lang.AssertionError: 
0 - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader


	at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:80)
	at au.com.dius.pact.provider.junit.target.AmqpTarget.testInteraction(AmqpTarget.kt:44)
	at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:236)
	at au.com.dius.pact.provider.junit.RunStateChanges.evaluate(RunStateChanges.java:31)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:169)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:118)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I'm using the following versions:
* java - 10.0.2
* maven - 3.5.4
* pact - 3.5.21
* pact-jvm-provider-junit_2.12 - 3.5.21

I've tried running the test through both IntelliJ and maven with the same result both times.

**Comment by uglyog** [comment]
Pact-JVM can only run on Java 8. Java 9 and later will be supported from version 4.0.0, which is a fair way off until that version will be implemented.

**Comment by Bjoern-Hegstam** [comment]
Ah, ok. I assumed it was already supported since the version table in the README specifies a Min JDK. But then I will hold off for the future 4.0.0. Thank you for responding.

**Comment by pkubowicz** [comment]
HTTP target works fine. I use `pact-jvm-provider-junit_2.12:3.5.23` with Java 10.0.2 and haven't met any problems. The same for Junit5 variant.

**Comment by uglyog** [comment]
4.0.0-beta.1 has been released which runs on JDK 8 to 11
