### ISSUE TITLE
`UnsupportedOperationException: empty.reduceLeft` when repeating an interaction

### ISSUE THREAD

**Issue by seanf** [DiUS/pact-jvm#78]
I have modified a copy of `au.com.dius.pact.consumer.ExampleJavaConsumerPactTest` to invoke "OPTIONS /second" a second time during `runTest`, but instead of getting the response again, or a meaningful error message, I get an exception.

(I would actually like to set up a pact to get a different response the second time for the request, which may or may not agree with Pact's philosophy, but this is the simplest case which produces the exception. I got no error when I tried to build a PactFragment with such a duplicate response, only when the test was run.  If it is not supported, it would be better to reject it immediately.)

The modified test looks like this:

            assertEquals(new ConsumerClient(url).options("/second"), 200);
            Map expectedResponse = new HashMap();
            expectedResponse.put("responsetest", true);
            expectedResponse.put("name", "harry");
            assertEquals(new ConsumerClient(url).get("/"), expectedResponse);
            assertEquals(new ConsumerClient(url).options("/second"), 200);

This is the exception I get (using pact-jvm-consumer-junit_2.11 2.1.8):

    java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:165)
	at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$reduceLeft(ArrayBuffer.scala:48)
	at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
	at scala.collection.mutable.ArrayBuffer.reduceLeft(ArrayBuffer.scala:48)
	at au.com.dius.pact.model.RequestMatching.matchInteraction(RequestMatching.scala:12)
	at au.com.dius.pact.consumer.PactSession.receiveRequest(PactSession.scala:38)
	at au.com.dius.pact.consumer.StatefulMockProvider.handleRequest(MockProvider.scala:53)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$$anonfun$intent$1.applyOrElse(UnfilteredMockProvider.scala:25)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$$anonfun$intent$1.applyOrElse(UnfilteredMockProvider.scala:24)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:218)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:214)
	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
	at unfiltered.response.Pass$PassingAttempt$class.attempt(pass.scala:65)
	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
	at unfiltered.response.Pass$$anonfun$fold$1.apply(pass.scala:48)
	at unfiltered.response.Pass$FunctionAttempt.apply(pass.scala:77)
	at unfiltered.netty.cycle.Plan$$anonfun$channelRead$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(plans.scala:70)
	at unfiltered.netty.cycle.Plan$class.catching(plans.scala:44)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$.catching(UnfilteredMockProvider.scala:20)
	at unfiltered.netty.cycle.Plan$$anonfun$channelRead$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(plans.scala:69)
	at unfiltered.netty.cycle.SynchronousExecution$class.executeIntent(deferrals.scala:23)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$.executeIntent(UnfilteredMockProvider.scala:20)
	at unfiltered.netty.cycle.Plan$$anonfun$channelRead$1.apply$mcV$sp(plans.scala:68)
	at unfiltered.netty.cycle.Plan$class.catching(plans.scala:44)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$.catching(UnfilteredMockProvider.scala:20)
	at unfiltered.netty.cycle.Plan$class.channelRead(plans.scala:67)
	at au.com.dius.pact.consumer.UnfilteredMockProvider$Routes$.channelRead(UnfilteredMockProvider.scala:20)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by uglyog** [comment]
Is it ok to close this issue and agree that it won't be implemented?

**Comment by seanf** [comment]
I think a better error message would still be a good idea, in any case.

**Comment by bethesque** [comment]
I'm not prepared to put my money where my mouth is and fix this, but I reckon that an interaction should be able to be run more than once (ignoring other changes to functionality that we discussed.) Would this be a big effort?

**Comment by thetrav** [comment]
The big problem I can see with that, is that when you allow the interaction to run multiple times, you're making an un-stated (and therefore untested) assertion that the interaction does not meaningfully change state.

The immediate example that springs to mind is that the first DELETE will likely respond with a 2xx code, for the first call and a 4xx code for the second.

I thoroughly agree that the error message should be improved

**Comment by uglyog** [comment]
When you refer to "a better error message", do you mean the original exception (which has been fixed), or a better error to indicate you are using the same description for two different requests?

**Comment by thetrav** [comment]
I was referring to "empty.reduceLeft" sorry I didn't realise it had already been improved

**Comment by uglyog** [comment]
The error message won't occur now (fixed in f71f7d3)
