### ISSUE TITLE
gradle pact not working after upgrade to gradle 4.8

### ISSUE THREAD

**Issue by parthibanrey** [DiUS/pact-jvm#781]
Synchronize Gradle projects with workspace failed due to an error in the referenced Gradle build.
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.8-bin.zip'.

A problem occurred configuring root project 'wag-doc-text2clip'.
**No signature of method: org.gradle.util.NameValidator.asValidName() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [pactVerify_text2clip]**
**org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.8-bin.zip'.**
    at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'wag-doc-text2clip'.
    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:109)
    at 
Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.util.NameValidator.asValidName() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [pactVerify_text2clip]
    at au.com.dius.pact.provider.gradle.PactPlugin$_apply_closure1$_closure3$_closure4.doCall(PactPlugin.groovy:47)
    at 

Can someone help me please.

**Comment by parthibanrey** [comment]
Resolved this issue by upgrading the pact plugin.

id "au.com.dius.pact" version "3.6.0-rc.0"

classpath "gradle.plugin.au.com.dius:pact-jvm-provider-gradle_2.12:3.6.0-rc.0"
