### ISSUE TITLE
Failed to invoke pact method on create object in PactDslBody with messages consumer test

### ISSUE THREAD

**Issue by Artem034** [DiUS/pact-jvm#808]
Hi there,  
when I write message pact method for generate contract, I get "failed to invoke pact" method on creating object(body.object) in PactDslBody.
Note: If don`t use body.object it works as usual.
 Please see code below.
`@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
public class ConsumerTest {

    @Rule
    public MessagePactProviderRule mockProvider = new MessagePactProviderRule(this);
    @Autowired
    private Consumer consumer;

    List<Product> getProductList() {
        List<Product> products = new ArrayList<Product>();
        products.add(new Product("123", new Category("456"), new ArrayList<Specification>()));
        return products;
    }

    @Pact(provider = "provider", consumer = "Consumer service")
    public MessagePact pimCreatedMessagePact(MessagePactBuilder messagePactBuilder) {

        PactDslJsonBody body = new PactDslJsonBody();
        body.object("payload"); // error here!
        body.stringValue("id","123123");
        body.stringValue("category", "123");
        body.stringValue("specification","null");
        body.closeObject();

        return messagePactBuilder
                .expectsToReceive("pim-adapter created message")
                .withContent(body)
                .toPact();
    }

    @Test
    @PactVerification("Provider create message")
    public void verifyCreatePersonPact() throws InterruptedException {
        consumer.handle(new ArrayList<Product>(this.getProductList()));
    }

    /**
     * This method is called by the Pact framework.
     */
    public void setMessage(List<Product> products) {
        products = getProductList();
    }
}
`
Stack trace 
`java.lang.RuntimeException: Failed to invoke pact method

	at au.com.dius.pact.consumer.MessagePactProviderRule.parsePacts(MessagePactProviderRule.java:179)
	at au.com.dius.pact.consumer.MessagePactProviderRule.access$500(MessagePactProviderRule.java:23)
	at au.com.dius.pact.consumer.MessagePactProviderRule$1.evaluate(MessagePactProviderRule.java:84)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at au.com.dius.pact.consumer.MessagePactProviderRule.parsePacts(MessagePactProviderRule.java:176)
	... 26 more
Caused by: java.lang.NoSuchMethodError: scala.util.parsing.combinator.Parsers.$init$(Lscala/util/parsing/combinator/Parsers;)V
	at io.gatling.jsonpath.Parser$.<init>(Parser.scala:49)
	at io.gatling.jsonpath.Parser$.<clinit>(Parser.scala)
	at au.com.dius.pact.consumer.dsl.PactDslJsonBody.object(PactDslJsonBody.java:538)
	at com.gravtcy.app.ConsumerTest.pimCreatedMessagePact(ConsumerTest.java:45)
	... 31 more
`

**Comment by Artem034** [comment]
Hi @yurkalt, downgrade Scala version is help me, thanks!
