### ISSUE TITLE
No such property: message for class:  java.lang.String

### ISSUE THREAD

**Issue by RusmanCool** [DiUS/pact-jvm#831]
_**How can I get a meaningful error in a console/report?**_
Trying to verify Java 8 **Provider** against pact file in json format. I have not added proper endpoints yet on purpose to see helpful errors. Instead, I am getting:
```
returns a response which
      Request Failed - No such property: message for class: java.lang.String"
```

```
For a Response that is returned by Provider SpringBoot server:
au.com.dius.pact.provider.ProviderClient - Response: {statusCode=404, headers={Content-Type=application/json;charset=UTF-8, Transfer-Encoding=chunked, Date=Wed, 12 Dec 2018 21:51:44 GMT}, contentType=application/json; charset=UTF-8, data={"timestamp":"2018-12-12T21:51:44.359+0000","status":404,"error":"Not Found","message":"No message available","path":"/api/application/"}}
```
I have traced it back to `ProviderVerification.class` line 199.

I am using

```xml
                <dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-provider-junit_2.12</artifactId>
			<version>3.6.0</version>
		</dependency>
```
Full response from Pact:

```
Verifying a pact between CreditCardApplicaionApiClient and CreditCardApplicaionApi
  Given A CC application has already been submitted by a member
  A POST request to retrieve a submitted by a member cc application 
16:51:44.354 [main] DEBUG au.com.dius.pact.provider.ProviderClient - Making request for provider au.com.dius.pact.provider.ProviderInfo(http, localhost, 8806, /, CreditCardApplicaionApi, null, null, null, null, null, false, null, changeit, null, true, false, true, null, [], []):
16:51:44.354 [main] DEBUG au.com.dius.pact.provider.ProviderClient - 	method: POST
	path: /api/application/
	query: [:]
	headers: [Accept:application/json, Content-Type:application/json; charset=utf-8]
	matchers: MatchingRules(rules={})
	generators: Generators(categories={})
	body: OptionalBody(state=PRESENT, value={"MemberAccessNumber":"5794684"})
16:51:44.360 [main] DEBUG au.com.dius.pact.provider.ProviderClient - Received response: HTTP/1.1 404 
16:51:44.361 [main] DEBUG au.com.dius.pact.provider.ProviderClient - Response: {statusCode=404, headers={Content-Type=application/json;charset=UTF-8, Transfer-Encoding=chunked, Date=Wed, 12 Dec 2018 21:51:44 GMT}, contentType=application/json; charset=UTF-8, data={"timestamp":"2018-12-12T21:51:44.359+0000","status":404,"error":"Not Found","message":"No message available","path":"/api/application/"}}
16:51:44.364 [main] DEBUG au.com.dius.pact.matchers.HeaderMatcher - Comparing header 'Content-Type': 'application/json;charset=UTF-8' to 'application/json; charset=utf-8'
16:51:44.368 [main] DEBUG au.com.dius.pact.matchers.HeaderMatcher - Comparing content type header: 'application/json;charset=UTF-8' to 'application/json; charset=utf-8'
16:51:44.374 [main] DEBUG au.com.dius.pact.model.Matching$ - Found a matcher for application/json -> au.com.dius.pact.matchers.JsonBodyMatcher@dc4a691
    returns a response which
      Request Failed - No such property: message for class: java.lang.String

Failures:

0) A POST request to retrieve a submitted by a member cc application 
      No such property: message for class: java.lang.String
```
And JUnit stack trace:

```
java.lang.AssertionError: 
0 - No such property: message for class: java.lang.String

	at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.kt:71)
	at au.com.dius.pact.provider.junit.target.HttpTarget.testInteraction(HttpTarget.kt:80)
	at au.com.dius.pact.provider.junit.InteractionRunner$interactionBlock$statement$1.evaluate(InteractionRunner.kt:207)
	at au.com.dius.pact.provider.junit.RunStateChanges.evaluate(RunStateChanges.kt:17)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.kt:143)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:137)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)


```
And the Pact file:

```json
{
  "consumer": {
    "name": "CreditCardApplicaionApiClient"
  },
  "provider": {
    "name": "CreditCardApplicaionApi"
  },
  "interactions": [
    {
      "description": "A POST request to retrieve a submitted by a member cc application ",
      "providerState": "A CC application has already been submitted by a member",
      "request": {
        "method": "post",
        "path": "/api/application/",
        "headers": {
          "Accept": "application/json",
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "MemberAccessNumber": "5794684"
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "MemberAccessNumber": "5794684",
          "CreditLimit": "1500"
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

**Comment by uglyog** [comment]
This has been released with version 3.6.2
