### ISSUE TITLE
using pactbroker always results in 401 Unauthorized

### ISSUE THREAD

**Issue by KasparScherrer** [DiUS/pact-jvm#881]
I'm fairly new to pact and I am trying to validate a pact that was published by the consumer on our pactbroker which is hosted on dius. 

I do it with the pact-jvm-provider-junit5, and I was able to successfully validate the pact when I had a local .json file of the pact and when I used `@PactFolder` to point to the location of that local file.

However, when I now try to use our broker, I always get the message   
> au.com.dius.pact.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 401 Unauthorized'"

Here is my @PactBroker annotation:
```
@PactBroker(
        host="myorg.pact.dius.com.au",
        port="443",
        scheme = "https",
        authentication = @PactBrokerAuth(username = "foo@bar.com", password = "foobar")
)
``` 
where the user in the `@PactBrokerAuth` is the one that I use for logging into the broker ui.  Is this the wrong user? I see in the broker ui there are tokens for read-only and read-write, maybe I need to use one of those (but how)?   

**Edit:** I am now pretty sure I need to supply the read-only token as a Bearer-Token (I tested it with postman with success, in contrast to using basic auth with my actual username and password). But the @PactBroker's authentication property is of Type PactBrokerAuth, which in turn has a **required username and password**, so I don't see a way to provide that Bearer Token.
End Edit.

I have searched far and wide to resolve this, and tried all variations of parameters, but nobody seems to have that same problem. I have tried the [pact maven plugin](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-maven) but there also I did not get further than the 401 Unauthorized error.

If this is not a bug but a wrong use by me I apologize. But in my defense I must say, the documentation confuses me quite a lot, and I am at my wit's end - I really tried my best, for almost 2 days now, without success. 

--------- 
full stack trace:
```
au.com.dius.pact.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 401 Unauthorized'

	at au.com.dius.pact.pactbroker.HalClientBase.getJson(HalClient.kt:248)
	at au.com.dius.pact.pactbroker.HalClientBase.fetch(HalClient.kt:223)
	at au.com.dius.pact.pactbroker.HalClientBase.fetch(HalClient.kt:218)
	at au.com.dius.pact.pactbroker.HalClientBase.navigate(HalClient.kt:211)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at au.com.dius.pact.provider.broker.PactBrokerClient.fetchConsumers(PactBrokerClient.groovy:40)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.java:141)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:84)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.provideTestTemplateInvocationContexts(PactJUnit5VerificationProvider.kt:336)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$0(TestTemplateTestDescriptor.java:97)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
```

**Comment by uglyog** [comment]
It definitely will work with basic auth. Maybe double check your credentials.

You can use the bearer tokens as well, just set the scheme attribute on the PactBrokerAuth annotation to bearer and the token value in the username attribute. Leave the password out, or blank.

**Comment by mefellows** [comment]
@KasparScherrer Looks like you might be using your email/password to authenticate - this is just for logging into the UI.  From there you can generate an API token that you can use instead. If you are authenticating to your broker with email/password then basic auth isn't an option for you.

**Comment by KasparScherrer** [comment]
> It definitely will work with basic auth. Maybe double check your credentials.

Believe me I checked the credentials. doesn't work.


> You can use the bearer tokens as well, just set the scheme attribute on the PactBrokerAuth annotation to bearer and the token value in the username attribute. Leave the password out, or blank.

**This works!** Its very strange though to put the token in the username and leaving the password empty , I surely would not have thought to try this out any time soon.  But now I know, and hey it works :)

Thank you very much for the fast and helpful reply. I'm closing this now.

**Comment by uglyog** [comment]
Sorry, I see things have changed and basic auth now doesn’t work. I need to create a BearerToken annotation when I have a chance.
