### ISSUE TITLE
dependencies.dependency au.com.dius:pact-jvm-model:3.6.5' for au.com.dius:pact-jvm-model:3.6.5 is referencing itself. @ line 170, column 17

### ISSUE THREAD

**Issue by Sam-Levene** [DiUS/pact-jvm#884]
```
Me@HERE: <CURRENT-WORKING-DIR>
$> mvn surefire-report:report test site
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.ExampleTest
<...>
46 Scenarios (46 passed)
107 Steps (107 passed)

[FATAL] 'dependencies.dependency au.com.dius:pact-jvm-model:3.6.5' for au.com.dius:pact-jvm-model:3.6.5 is referencing itself. @ line 170, column 17
 for project au.com.dius:pact-jvm-model:3.6.5
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:165)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:327)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:125)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderArtifactRow(DependenciesRenderer.java:799)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderDependenciesForScope(DependenciesRenderer.java:749)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderDependenciesForAllScopes(DependenciesRenderer.java:413)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionProjectTransitiveDependencies(DependenciesRenderer.java:438)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:219)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:80)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:162)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for au.com.dius:pact-jvm-model:3.6.5
```

Hi, so the above occurs after maven has run the tests (which run successfully) but before Surefire Report generates. (Which also runs successfully)

Here's my POM:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>[REDACTED]</groupId>
  <artifactId>[REDACTED]</artifactId>
  <version>0.0.1-SNAPSHOT</version>
	<properties>
    	<maven.compiler.source>1.8</maven.compiler.source>
    	<maven.compiler.target>1.8</maven.compiler.target>
  	</properties>
  <build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-site-plugin</artifactId>
      <version>3.7.1</version>
    </plugin>
    <plugin>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.1</version>
    </plugin>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>3.0.0-M3</version>
    </plugin>
    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.2.1</version>
        <executions>
            <execution>
                <goals>
                    <goal>exec</goal>
                </goals>
                <configuration>
                    <classpathScope>test</classpathScope>
                    <executable>java</executable>
                    <arguments>
                        <argument>-classpath</argument>
                        <classpath />
                        <argument>cucumber.api.cli.Main</argument>
                        <argument>--plugin</argument>
                        <argument>json:${project.build.directory}/cuke-results.json</argument>
                        <argument>--glue</argument>
                        <argument>com.example</argument>
                        <argument>--strict</argument>
                        <argument>${basedir}/src/test/java/com/example</argument>
                    </arguments>
                </configuration>
            </execution>
        </executions>
    </plugin>
  </plugins>
  </build>
  <dependencies>
	<dependency>
	    <groupId>au.com.dius</groupId>
	    <artifactId>pact-jvm-consumer-junit_2.12</artifactId>
	    <version>3.6.5</version>
	</dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
	  <artifactId>rest-assured</artifactId>
	  <version>3.3.0</version>
	</dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
    </dependency>
    <dependency>
      <groupId>info.cukes</groupId>
      <artifactId>cucumber-java</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>info.cukes</groupId>
      <artifactId>cucumber-junit</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
	  <groupId>org.json</groupId>
	  <artifactId>json</artifactId>
	  <version>20180813</version>
	</dependency>
  </dependencies>
</project>
```

**Comment by Sam-Levene** [comment]
Sweet. Let me know when this gets released :D

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
