### ISSUE TITLE
json and markdown reports don't show multiple interaction

### ISSUE THREAD

**Issue by anddreiu** [DiUS/pact-jvm#893]
I am using pact-jvm-provider-junit_2.12 version 3.6.5. I have two interactions in my pact file, but when I run the provider test, in the json and markdown generated reports it appears just the last interaction.

This is how my pact file looks like:

`{
	"provider": {
		"name": "provider1"
	},
	"consumer": {
		"name": "consumer1"
	},
	"interactions": [
		{
			"description": "First interaction",
                        ............
                },
                {
			"description": "Second interaction",
                        ............
                }
          ]
`

After running the test, just the second iteration is displayed in the json and markdown reports. Below you can see an example from the markdown report.

`# provider1

| Description    | Value |
| -------------- | ----- |
| Date Generated | Fri Jun 14 15:29:26 EEST 2019 |
| Pact Version   | 3.6.5 |

## Verifying a pact between consumer1 and provider1

Given **Second interaction**  
......
`
Is this an issue or am I doing something wrong?

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix

**Comment by anddreiu** [comment]
Thanks uglyog for the fix. I have just tried to run the test using 3.6.8 version, but I have some other issue now - not sure if it's related to your fix or it's something else. I have run again with 3.6.7 and the test runs ok, but when trying with 3.6.8, the test fails at the initialization phase when the pact is loaded from the Pact Broker.

Below you can see the full stacktrace when running the test from the IDE. Same thing happens when running the provider test using mvn test command.

`groovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.toInt() is applicable for argument types: () values: []
Possible solutions: print(java.io.PrintWriter), print(java.lang.Object), toLong(), round(java.math.MathContext), downto(java.lang.Number, groovy.lang.Closure), downto(java.lang.Number, groovy.lang.Closure)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.Response$_fromMap_closure1.doCall(Response.groovy:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:242)
	at org.codehaus.groovy.runtime.dgm$757.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.Response.fromMap(Response.groovy:26)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.PactReader.extractResponse(PactReader.groovy:96)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.PactReader$_loadV3Pact_closure1.doCall(PactReader.groovy:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
	at org.codehaus.groovy.runtime.dgm$66.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.PactReader.loadV3Pact(PactReader.groovy:58)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy:41)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPact(PactBrokerLoader.java:181)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.lambda$loadPactsForProvider$3(PactBrokerLoader.java:164)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.java:165)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.java:84)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.kt:79)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:525)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

`

**Comment by uglyog** [comment]
Oh, damn! Sorry, I'll fix that immediately.

**Comment by anddreiu** [comment]
Great, thanks a lot @uglyog 
Do you know when it will be part of a new release?

**Comment by uglyog** [comment]
I'll get one out this week

**Comment by uglyog** [comment]
3.6.9 has been released with this fix

**Comment by anddreiu** [comment]
Great, many thanks!
