### ISSUE TITLE
java.lang.ClassCastException: class java.lang.AssertionError cannot be cast to class java.lang.Exception

### ISSUE THREAD

**Issue by dimovelev** [DiUS/pact-jvm#935]
In 4.0.0-beta.6 I get the following exception when I try to execute the provider tests:
```
java.lang.ClassCastException: class java.lang.AssertionError cannot be cast to class java.lang.Exception (java.lang.AssertionError and java.lang.Exception are in module java.base of loader 'bootstrap')

	at au.com.dius.pact.core.pactbroker.PactBrokerClient.buildPayload(PactBrokerClient.kt:243)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.publishVerificationResults(PactBrokerClient.kt:167)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.publishVerificationResults$default(PactBrokerClient.kt:162)
	at au.com.dius.pact.provider.DefaultVerificationReporter.publishResult(VerificationReporter.kt:45)
	at au.com.dius.pact.provider.DefaultVerificationReporter.reportResults(VerificationReporter.kt:32)
	at au.com.dius.pact.provider.VerificationReporter$DefaultImpls.reportResults$default(VerificationReporter.kt:14)
	at au.com.dius.pact.provider.DefaultTestResultAccumulator.updateTestResult(TestResultAccumulator.kt:48)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.kt:157)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:137)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
Why dont we just cast to Throwable which is base class for both Exception and Error?

**Comment by uglyog** [comment]
4.0.0 has been released with this fix
