### ISSUE TITLE
Getting NoSuchMethodError when running PactConsumerTest

### ISSUE THREAD

**Issue by paolodm** [DiUS/pact-jvm#98]
```
java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at au.com.dius.pact.model.Request$.apply(Pact.scala:195)
	at au.com.dius.pact.consumer.ConsumerPactBuilder$PactDslResponse.addInteraction(ConsumerPactBuilder.java:509)
	at au.com.dius.pact.consumer.ConsumerPactBuilder$PactDslResponse.toFragment(ConsumerPactBuilder.java:531)
	at ConsumerPactTest.createFragment(ConsumerPactTest.java:19)
	at au.com.dius.pact.consumer.ConsumerPactTest.testPact(ConsumerPactTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

The java code:

```java
package service.questionnaire;


import java.util.HashMap;
import java.util.Map;
import au.com.dius.pact.consumer.ConsumerPactBuilder;
import au.com.dius.pact.consumer.ConsumerPactTest;
import au.com.dius.pact.model.PactFragment;

import static org.junit.Assert.assertEquals;

public class StatusServiceConsumerPactTest extends ConsumerPactTest {

    @Override
    protected PactFragment createFragment(ConsumerPactBuilder.PactDslWithProvider builder) {
        Map<String, String> headers = new HashMap();
        headers.put("testreqheader", "testreqheadervalue");

        return builder
            .uponReceiving("status")
            .path("/status")
            .method("GET")
            .headers(headers)
            .body("{\"test\":true}")
            .willRespondWith()
            .status(200)
            .headers(headers)
            .body("{\"responsetest\":true}").toFragment();
    }

    @Override
    protected String providerName() {
        return "provider";
    }

    @Override
    protected String consumerName() {
        return "consumer";
    }

    @Override
    protected void runTest(String s) {
        try {
            StatusServiceClient statusServiceClient = new StatusServiceClient();

            String currentQuestionnairePage = statusServiceClient.getCurrentQuestionnairePage(null);

            assertEquals(currentQuestionnairePage, "my_home_1");
        } catch (Exception e) {
            // NOTE: if you want to see any pact failure, do not throw an exception here. This should be
            // fixed at some point (see Issue #40 https://github.com/DiUS/pact-jvm/issues/40)
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by uglyog** [comment]
I'm unable to replicate this issue. I have added your example test, can you please look at it (the commit is attached to this issue). It runs correctly against both pact-jvm-consumer-junit_2.11 and pact-jvm-consumer-junit_2.10.

Can you let me know what OS and java version you are using? Also what build tool or IDE you are using to run the test.

One thing I have noticed is that the example was not technally correct, as GET requests can not have a body. But I don't think this will cause the problem.

**Comment by uglyog** [comment]
If you are using gradle, it may be related to #110

**Comment by worldwar2008** [comment]
due to the version of scala

**Comment by uglyog** [comment]
which version of scala are you using?

**Comment by paolodm** [comment]
2.10.3

```
Scala code runner version 2.10.3 -- Copyright 2002-2013, LAMP/EPFL
```

**Comment by uglyog** [comment]
What do you use to run your tests?

**Comment by DeepSpawn** [comment]
So I just encountered this issue when running a project with IDEA intellij. The problem was an incorrect version of Scala was specified in the project settings. Changing to the correct version of Scala in project settings -> modules -> dependencies resolved it.

I encountered this after successfully running the consumer test, it was not exposed until I ran a maven clean:install
