### ISSUE TITLE
Adding headers when using MockMvcTarget

### ISSUE THREAD

**Issue by mstelz** [DiUS/pact-jvm#983]
When using `SpringRestPactRunner` and `MockMvcTarget` the `@TargetRequestFilter` is never being invoked so I am not able to add headers. Is there another way? It looks like `@TargetRequestFilter` only works when using `HttpTarget`

```java
@RunWith(SpringRestPactRunner.class)
@Provider("provider-name")
@PactBroker
public class PactVerificationTest {

    @Mock
    private MockedService mockedService;

    @InjectMocks
    private MyController controller = new MyController(mockedService);

    @TestTarget
    public final MockMvcTarget target = new MockMvcTarget();

    @Before
    public void before() {
        //initialize your mocks using your mocking framework
        MockitoAnnotations.initMocks(this);

        //configure the MockMvcTarget with your controller and controller advice
        target.setControllers(controller);
        target.setPrintRequestResponse(true);
    }

    // This block is never invoked
    @TargetRequestFilter
    public void requestFilter(HttpRequest request) {
        request.addHeader("Content-Type", MediaType.APPLICATION_JSON_VALUE);
    }

    @State({"person"})
    public void verify() throws DownstreamServiceException {
        target.setRunTimes(1);
        // ... mockito mocks
    }
}
```

**Comment by uglyog** [comment]
I've added support for request filters, but the parameter will be an instance of `MockHttpServletRequestBuilder` not `HttpRequest`

**Comment by mstelz** [comment]
what is the release schedule? is a new release going to be cut soon?

**Comment by mtstelz** [comment]
With the latest release 4.0.4 using the following code: 

```java
@RunWith(SpringRestPactRunner.class)
@Provider("provider-name")
@PactBroker
public class PactVerificationTest {

    @Mock
    private MockedService mockedService;

    @InjectMocks
    private MyController controller = new MyController(mockedService);

    @TestTarget
    public final MockMvcTarget target = new MockMvcTarget();

    @Before
    public void before() {
        //initialize your mocks using your mocking framework
        MockitoAnnotations.initMocks(this);

        //configure the MockMvcTarget with your controller and controller advice
        target.setControllers(controller);
        target.setPrintRequestResponse(true);
    }

    @TargetRequestFilter
    public void requestFilter(MockHttpServletRequestBuilder request) {
        request.header("Content-Type", MediaType.APPLICATION_JSON_VALUE);
    }

    @State({"person"})
    public void verify() throws DownstreamServiceException {
        target.setRunTimes(1);
        // ... mockito mocks
    }
}
```

I get the following error: 
```
java.lang.Exception: Method requestFilter should take only a single HttpRequest parameter

	at au.com.dius.pact.provider.junit.InteractionRunner.validateTargetRequestFilters(InteractionRunner.kt:102)
	at au.com.dius.pact.provider.junit.InteractionRunner.validate(InteractionRunner.kt:89)
	at au.com.dius.pact.provider.junit.InteractionRunner.<init>(InteractionRunner.kt:60)
	at au.com.dius.pact.provider.spring.SpringInteractionRunner.<init>(SpringInteractionRunner.kt:77)
	at au.com.dius.pact.provider.spring.SpringRestPactRunner.newInteractionRunner(SpringRestPactRunner.kt:52)
	at au.com.dius.pact.provider.junit.PactRunner.setupInteractionRunners(PactRunner.kt:116)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.kt:110)
	at au.com.dius.pact.provider.junit.RestPactRunner.<init>(RestPactRunner.kt:8)
	at au.com.dius.pact.provider.spring.SpringRestPactRunner.<init>(SpringRestPactRunner.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by mstelz** [comment]
With the latest release 4.0.4 using the following code: 

```java
@RunWith(SpringRestPactRunner.class)
@Provider("provider-name")
@PactBroker
public class PactVerificationTest {

    @Mock
    private MockedService mockedService;

    @InjectMocks
    private MyController controller = new MyController(mockedService);

    @TestTarget
    public final MockMvcTarget target = new MockMvcTarget();

    @Before
    public void before() {
        //initialize your mocks using your mocking framework
        MockitoAnnotations.initMocks(this);

        //configure the MockMvcTarget with your controller and controller advice
        target.setControllers(controller);
        target.setPrintRequestResponse(true);
    }

    @TargetRequestFilter
    public void requestFilter(MockHttpServletRequestBuilder request) {
        request.header("Content-Type", MediaType.APPLICATION_JSON_VALUE);
    }

    @State({"person"})
    public void verify() throws DownstreamServiceException {
        target.setRunTimes(1);
        // ... mockito mocks
    }
}
```

I get the following error: 
```
java.lang.Exception: Method requestFilter should take only a single HttpRequest parameter

	at au.com.dius.pact.provider.junit.InteractionRunner.validateTargetRequestFilters(InteractionRunner.kt:102)
	at au.com.dius.pact.provider.junit.InteractionRunner.validate(InteractionRunner.kt:89)
	at au.com.dius.pact.provider.junit.InteractionRunner.<init>(InteractionRunner.kt:60)
	at au.com.dius.pact.provider.spring.SpringInteractionRunner.<init>(SpringInteractionRunner.kt:77)
	at au.com.dius.pact.provider.spring.SpringRestPactRunner.newInteractionRunner(SpringRestPactRunner.kt:52)
	at au.com.dius.pact.provider.junit.PactRunner.setupInteractionRunners(PactRunner.kt:116)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.kt:110)
	at au.com.dius.pact.provider.junit.RestPactRunner.<init>(RestPactRunner.kt:8)
	at au.com.dius.pact.provider.spring.SpringRestPactRunner.<init>(SpringRestPactRunner.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by vpsouza** [comment]
@mstelz still doesn't work for PactVerificationInvocationContextProvider

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change

**Comment by mstelz** [comment]
works thanks!
